# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpXi6y5V93QqLnpYkY7QIZBiiGqwaggy
"""

!pip install gradio anthropic -q

UI_STRINGS = {
    "English": {
        "step2": "🤰 Are you pregnant?", "yes": "Yes 🤰", "no": "No",
        "step3": "🫀 Where does it hurt?", "step4": "🔴 What are you feeling?",
        "placeholder": "e.g. stomach pain for 3 days, periods irregular...",
        "btn": "🔍 Ask Sakhi", "urgent": "🚨 URGENT — Go to a doctor TODAY",
        "moderate": "⚡ ATTENTION — See a doctor within 2–3 days",
        "normal": "✅ Manageable — Monitor and stay alert",
        "see_doctor": "Show this report to your nearest ASHA worker or doctor.",
        "screening": "🔬 Recommended Screenings", "recs_title": "💡 Recommendations",
        "red_flags": "🚨 Red Flags Detected", "maternal": "🤰 Pregnancy Alerts",
        "waiting": "🌸 Sakhi is waiting… select symptoms and click Ask Sakhi",
        "result": "Your SakhiAI Health Report",
    },
    "Hindi": {
        "step2": "🤰 क्या आप गर्भवती हैं?", "yes": "हाँ 🤰", "no": "नहीं",
        "step3": "🫀 कहाँ दर्द है?", "step4": "🔴 क्या महसूस हो रहा है?",
        "placeholder": "जैसे: 3 दिन से पेट दर्द है, माहवारी अनियमित है...",
        "btn": "🔍 सखी से पूछें", "urgent": "🚨 ज़रूरी — आज ही डॉक्टर के पास जाएं",
        "moderate": "⚡ ध्यान दें — 2-3 दिन में डॉक्टर से मिलें",
        "normal": "✅ ठीक है — रोज़ ट्रैक करें और सतर्क रहें",
        "see_doctor": "यह रिपोर्ट अपनी ASHA वर्कर या डॉक्टर को दिखाएं।",
        "screening": "🔬 ज़रूरी जाँचें", "recs_title": "💡 सलाह",
        "red_flags": "🚨 गंभीर लक्षण", "maternal": "🤰 गर्भावस्था चेतावनी",
        "waiting": "🌸 सखी इंतज़ार कर रही है… लक्षण चुनें और पूछें",
        "result": "आपकी SakhiAI स्वास्थ्य रिपोर्ट",
    },
    "Tamil": {
        "step2": "🤰 நீங்கள் கர்ப்பமாக இருக்கிறீர்களா?", "yes": "ஆம் 🤰", "no": "இல்லை",
        "step3": "🫀 வலி எங்கே உள்ளது?", "step4": "🔴 என்ன உணர்கிறீர்கள்?",
        "placeholder": "எ.கா. 3 நாட்களாக வயிற்று வலி...",
        "btn": "🔍 சகியிடம் கேளுங்கள்", "urgent": "🚨 அவசரம் — இன்றே மருத்துவரை பாருங்கள்",
        "moderate": "⚡ கவனம் — 2-3 நாட்களில் மருத்துவரை சந்தியுங்கள்",
        "normal": "✅ சாதாரணம் — கண்காணித்து விழிப்பாக இருங்கள்",
        "see_doctor": "இந்த அறிக்கையை ASHA பணியாளர் அல்லது மருத்துவரிடம் காட்டுங்கள்.",
        "screening": "🔬 பரிந்துரைக்கப்பட்ட பரிசோதனைகள்", "recs_title": "💡 ஆலோசனைகள்",
        "red_flags": "🚨 கடுமையான அறிகுறிகள்", "maternal": "🤰 கர்ப்பகால எச்சரிக்கை",
        "waiting": "🌸 சகி காத்திருக்கிறாள்… அறிகுறிகளை தேர்ந்தெடுத்து கேளுங்கள்",
        "result": "உங்கள் SakhiAI சுகாதார அறிக்கை",
    },
    "Bengali": {
        "step2": "🤰 আপনি কি গর্ভবতী?", "yes": "হ্যাঁ 🤰", "no": "না",
        "step3": "🫀 কোথায় ব্যথা?", "step4": "🔴 কী অনুভব করছেন?",
        "placeholder": "যেমন: ৩ দিন ধরে পেটে ব্যথা, মাসিক অনিয়মিত...",
        "btn": "🔍 সখীকে জিজ্ঞেস করুন", "urgent": "🚨 জরুরি — আজই ডাক্তার দেখুন",
        "moderate": "⚡ মনোযোগ — ২-৩ দিনের মধ্যে ডাক্তার দেখুন",
        "normal": "✅ ঠিক আছে — প্রতিদিন পর্যবেক্ষণ করুন",
        "see_doctor": "এই রিপোর্ট ASHA কর্মী বা ডাক্তারকে দেখান।",
        "screening": "🔬 প্রস্তাবিত পরীক্ষা", "recs_title": "💡 পরামর্শ",
        "red_flags": "🚨 গুরুতর লক্ষণ", "maternal": "🤰 গর্ভাবস্থা সতর্কতা",
        "waiting": "🌸 সখী অপেক্ষা করছে… লক্ষণ বেছে নিন এবং জিজ্ঞেস করুন",
        "result": "আপনার SakhiAI স্বাস্থ্য রিপোর্ট",
    },
}
print(f"✅ UI strings loaded for {len(UI_STRINGS)} languages")

SYMPTOMS = {
    "Head & Brain 🧠": {
        "English": [("Severe headache","red"),("Blurred vision","red"),("Dizziness / fainting","yellow"),("Mild headache","green"),("Forgetfulness","green")],
        "Hindi":   [("तेज़ सिरदर्द","red"),("धुंधला दिखना","red"),("चक्कर आना / बेहोशी","yellow"),("हल्का सिरदर्द","green"),("भूलना","green")],
        "Tamil":   [("கடுமையான தலைவலி","red"),("மங்கலான பார்வை","red"),("தலைசுற்றல் / மயக்கம்","yellow"),("லேசான தலைவலி","green"),("மறதி","green")],
        "Bengali": [("তীব্র মাথাব্যথা","red"),("ঝাপসা দৃষ্টি","red"),("মাথা ঘোরা / অজ্ঞান","yellow"),("হালকা মাথাব্যথা","green"),("ভুলে যাওয়া","green")],
    },
    "Chest & Heart 🫀": {
        "English": [("Chest pain / pressure","red"),("Shortness of breath","red"),("Heart palpitations","yellow"),("Mild chest tightness","yellow"),("Fatigue / tiredness","green")],
        "Hindi":   [("सीने में दर्द / दबाव","red"),("सांस लेने में तकलीफ","red"),("दिल की धड़कन तेज़","yellow"),("सीने में हल्की जकड़न","yellow"),("थकान","green")],
        "Tamil":   [("மார்பு வலி / அழுத்தம்","red"),("மூச்சு திணறல்","red"),("இதய படபடப்பு","yellow"),("லேசான மார்பு இறுக்கம்","yellow"),("சோர்வு","green")],
        "Bengali": [("বুকে ব্যথা / চাপ","red"),("শ্বাসকষ্ট","red"),("বুক ধড়ফড়","yellow"),("হালকা বুকের টান","yellow"),("ক্লান্তি","green")],
    },
    "Abdomen & Stomach 🫃": {
        "English": [("Severe abdominal pain","red"),("Persistent vomiting","yellow"),("Bloating / gas","green"),("Loss of appetite","yellow"),("Nausea","green")],
        "Hindi":   [("पेट में तेज़ दर्द","red"),("बार-बार उल्टी","yellow"),("पेट फूलना / गैस","green"),("भूख न लगना","yellow"),("जी मिचलाना","green")],
        "Tamil":   [("கடுமையான வயிற்று வலி","red"),("தொடர் வாந்தி","yellow"),("வயிறு உப்புசம் / வாயு","green"),("பசியின்மை","yellow"),("குமட்டல்","green")],
        "Bengali": [("তীব্র পেটব্যথা","red"),("বারবার বমি","yellow"),("পেট ফাঁপা / গ্যাস","green"),("খাবারে অরুচি","yellow"),("বমি বমি ভাব","green")],
    },
    "Pelvis & Reproductive ♀️": {
        "English": [("Unusual bleeding","red"),("Severe pelvic pain","red"),("Irregular periods","yellow"),("Unusual discharge","yellow"),("Pain during intercourse","yellow"),("Missed period","yellow")],
        "Hindi":   [("असामान्य रक्तस्राव","red"),("पेल्विस में तेज़ दर्द","red"),("अनियमित माहवारी","yellow"),("असामान्य स्राव","yellow"),("संभोग में दर्द","yellow"),("माहवारी न आना","yellow")],
        "Tamil":   [("அசாதாரண இரத்தப்போக்கு","red"),("கடுமையான இடுப்பு வலி","red"),("ஒழுங்கற்ற மாதவிடாய்","yellow"),("அசாதாரண வெளியேற்றம்","yellow"),("உடலுறவின்போது வலி","yellow"),("மாதவிடாய் தவறுதல்","yellow")],
        "Bengali": [("অস্বাভাবিক রক্তপাত","red"),("তীব্র শ্রোণী ব্যথা","red"),("অনিয়মিত মাসিক","yellow"),("অস্বাভাবিক স্রাব","yellow"),("সহবাসে ব্যথা","yellow"),("মাসিক না হওয়া","yellow")],
    },
    "Legs & Body 🦵": {
        "English": [("Swollen legs / ankles","red"),("Severe joint pain","yellow"),("Mild body ache","green"),("Numbness / tingling","yellow"),("Weakness","green")],
        "Hindi":   [("पैर / टखने सूजना","red"),("जोड़ों में तेज़ दर्द","yellow"),("हल्का बदन दर्द","green"),("सुन्न होना / झुनझुनी","yellow"),("कमज़ोरी","green")],
        "Tamil":   [("கால்கள் / கணுக்கால் வீக்கம்","red"),("கடுமையான மூட்டு வலி","yellow"),("லேசான உடல் வலி","green"),("மரத்துப்போதல் / கூச்சம்","yellow"),("பலவீனம்","green")],
        "Bengali": [("পা / গোড়ালি ফোলা","red"),("তীব্র জয়েন্ট ব্যথা","yellow"),("হালকা শরীর ব্যথা","green"),("অসাড়তা / ঝিনঝিন","yellow"),("দুর্বলতা","green")],
    },
    "Skin & General 🌡️": {
        "English": [("High fever (102°F+)","red"),("Unexplained weight loss","yellow"),("Skin rash / itching","yellow"),("Pale / yellowing skin","red"),("Mild fatigue","green")],
        "Hindi":   [("तेज़ बुखार (102°F+)","red"),("बिना कारण वज़न कम होना","yellow"),("त्वचा पर दाने / खुजली","yellow"),("पीली या सफ़ेद त्वचा","red"),("हल्की थकान","green")],
        "Tamil":   [("அதிக காய்ச்சல் (102°F+)","red"),("காரணமின்றி எடை குறைவு","yellow"),("தோல் தடிப்பு / அரிப்பு","yellow"),("வெளிர் / மஞ்சள் தோல்","red"),("லேசான சோர்வு","green")],
        "Bengali": [("তীব্র জ্বর (102°F+)","red"),("কারণ ছাড়া ওজন কমা","yellow"),("ত্বকে ফুসকুড়ি / চুলকানি","yellow"),("ফ্যাকাশে / হলুদ ত্বক","red"),("হালকা ক্লান্তি","green")],
    },
}

RED_FLAG_INFO = {
    "Unusual bleeding":      "Could indicate cervical or uterine issues. Early screening is critical.",
    "Severe pelvic pain":    "May indicate endometriosis, ovarian cyst, or ectopic pregnancy.",
    "Chest pain / pressure": "Women's heart attack symptoms are often dismissed. Do not ignore.",
    "Severe headache":       "Could indicate high blood pressure or neurological issue.",
    "Blurred vision":        "May indicate hypertension or gestational complications.",
    "Swollen legs / ankles": "Possible sign of preeclampsia if pregnant, or heart/kidney issue.",
    "Pale / yellowing skin": "May indicate severe anemia — very common and dangerous in women.",
    "High fever (102°F+)":   "Needs immediate attention — could be infection or severe illness.",
    "Severe abdominal pain": "Could indicate appendicitis, gallstones, or a reproductive issue.",
    "Shortness of breath":   "Can signal cardiac or respiratory emergency. Do not wait.",
}

MATERNAL_WARNINGS = {
    "Unusual bleeding":      "⚠️ Bleeding during pregnancy is always serious. Go to hospital NOW.",
    "Severe pelvic pain":    "⚠️ Could indicate miscarriage or ectopic pregnancy. Emergency care needed.",
    "Swollen legs / ankles": "⚠️ Sign of preeclampsia — dangerous in pregnancy. See doctor today.",
    "Severe headache":       "⚠️ Headache + pregnancy = possible preeclampsia. Do not wait.",
    "Blurred vision":        "⚠️ Vision changes in pregnancy need immediate evaluation.",
}

SCREENINGS = [
    "🩺 Cervical cancer (Pap smear) — every 3 years after age 21",
    "🩺 Breast cancer (self-exam monthly, mammogram after 40)",
    "🩺 Anaemia (haemoglobin check) — especially if fatigued",
    "🩺 Blood pressure — every 6 months",
    "🩺 Blood glucose — annually after age 30",
]

print("✅ Symptom data loaded!")

import json

def generate_health_report(language, is_pregnant, area, selected_symptoms, free_text):
    area_data    = SYMPTOMS.get(area, {})
    english_list = [s[0] for s in area_data.get("English", [])]
    native_list  = [s[0] for s in area_data.get(language, area_data.get("English", []))]
    sym_map      = dict(zip(native_list, english_list))
    english_syms = [sym_map.get(s, s) for s in selected_symptoms]

    red_flags       = {s: RED_FLAG_INFO[s] for s in english_syms if s in RED_FLAG_INFO}
    maternal_alerts = {s: MATERNAL_WARNINGS[s] for s in english_syms if is_pregnant and s in MATERNAL_WARNINGS}

    has_red = any(sev == "red" for nm, sev in area_data.get("English", []) if nm in english_syms)
    if maternal_alerts or (is_pregnant and has_red):
        urgency = "urgent"
    elif len([s for s in english_syms if s in RED_FLAG_INFO]) >= 2 or (has_red and len(english_syms) >= 2):
        urgency = "urgent"
    elif english_syms:
        urgency = "moderate" if (has_red or len(english_syms) >= 2) else "normal"
    else:
        urgency = "normal"

    # ── Rule-based recommendations ─────────────────────────
    RECS = {
        "English": {
            "urgent":   [
                "Go to the nearest government hospital or PHC immediately.",
                "Do not ignore these symptoms — they need urgent attention.",
                "Carry this report and show it to the doctor.",
            ],
            "moderate": [
                "Visit your nearest ASHA worker or PHC within 2–3 days.",
                "Note down when symptoms started and how often they occur.",
                "Avoid self-medication — consult a doctor first.",
            ],
            "normal":   [
                "Monitor your symptoms daily and note any changes.",
                "Maintain a balanced diet and drink enough water.",
                "Visit your ASHA worker if symptoms continue for more than a week.",
            ],
        },
        "Hindi": {
            "urgent":   [
                "तुरंत नज़दीकी सरकारी अस्पताल या PHC जाएं।",
                "इन लक्षणों को नज़रअंदाज़ न करें — तुरंत ध्यान ज़रूरी है।",
                "यह रिपोर्ट साथ ले जाएं और डॉक्टर को दिखाएं।",
            ],
            "moderate": [
                "2–3 दिन में अपनी ASHA वर्कर या PHC से मिलें।",
                "लक्षण कब शुरू हुए और कितनी बार होते हैं — यह नोट करें।",
                "बिना डॉक्टर की सलाह के कोई दवा न लें।",
            ],
            "normal":   [
                "रोज़ अपने लक्षणों पर ध्यान दें और बदलाव नोट करें।",
                "संतुलित खाना खाएं और पर्याप्त पानी पिएं।",
                "अगर लक्षण एक हफ़्ते से ज़्यादा रहें तो ASHA वर्कर से मिलें।",
            ],
        },
        "Tamil": {
            "urgent":   [
                "உடனே அருகிலுள்ள அரசு மருத்துவமனை அல்லது PHC செல்லுங்கள்.",
                "இந்த அறிகுறிகளை புறக்கணிக்காதீர்கள் — உடனடி கவனம் தேவை.",
                "இந்த அறிக்கையை எடுத்துச் சென்று மருத்துவரிடம் காட்டுங்கள்.",
            ],
            "moderate": [
                "2–3 நாட்களில் உங்கள் ASHA பணியாளர் அல்லது PHC ஐ சந்தியுங்கள்.",
                "அறிகுறிகள் எப்போது தொடங்கின என்று குறித்து வையுங்கள்.",
                "மருத்துவர் ஆலோசனை இல்லாமல் மருந்து எடுக்காதீர்கள்.",
            ],
            "normal":   [
                "தினமும் உங்கள் அறிகுறிகளை கவனியுங்கள்.",
                "சரிவிகித உணவு சாப்பிடுங்கள், போதுமான தண்ணீர் குடியுங்கள்.",
                "ஒரு வாரத்திற்கு மேல் அறிகுறிகள் தொடர்ந்தால் ASHA பணியாளரை சந்தியுங்கள்.",
            ],
        },
        "Bengali": {
            "urgent":   [
                "অবিলম্বে নিকটতম সরকারি হাসপাতাল বা PHC-তে যান।",
                "এই লক্ষণগুলো উপেক্ষা করবেন না — জরুরি মনোযোগ দরকার।",
                "এই রিপোর্ট সঙ্গে নিয়ে ডাক্তারকে দেখান।",
            ],
            "moderate": [
                "২–৩ দিনের মধ্যে ASHA কর্মী বা PHC-তে যান।",
                "লক্ষণ কখন শুরু হয়েছে এবং কতবার হচ্ছে তা লিখে রাখুন।",
                "ডাক্তারের পরামর্শ ছাড়া ওষুধ খাবেন না।",
            ],
            "normal":   [
                "প্রতিদিন আপনার লক্ষণগুলো পর্যবেক্ষণ করুন।",
                "সুষম খাবার খান এবং পর্যাপত পানি পান করুন।",
                "এক সপ্তাহের বেশি লক্ষণ থাকলে ASHA কর্মীর সাথে যোগাযোগ করুন।",
            ],
        },
    }

    SUMMARIES = {
        "English": {
            "urgent":   "Your symptoms need immediate medical attention. Please do not wait.",
            "moderate": "Your symptoms need attention. Please see a doctor soon.",
            "normal":   "Your symptoms seem manageable. Keep monitoring and stay alert.",
        },
        "Hindi": {
            "urgent":   "आपके लक्षण गंभीर हैं। कृपया तुरंत डॉक्टर से मिलें।",
            "moderate": "आपके लक्षणों पर ध्यान देना ज़रूरी है। जल्द डॉक्टर से मिलें।",
            "normal":   "आपके लक्षण अभी सामान्य लग रहे हैं। ध्यान रखें और सतर्क रहें।",
        },
        "Tamil": {
            "urgent":   "உங்கள் அறிகுறிகளுக்கு உடனடி மருத்துவ கவனிப்பு தேவை.",
            "moderate": "உங்கள் அறிகுறிகளுக்கு கவனிப்பு தேவை. விரைவில் மருத்துவரை பாருங்கள்.",
            "normal":   "உங்கள் அறிகுறிகள் இப்போது சாதாரணமாக தெரிகின்றன. கண்காணியுங்கள்.",
        },
        "Bengali": {
            "urgent":   "আপনার লক্ষণগুলোর জন্য তাৎক্ষণিক চিকিৎসা প্রয়োজন।",
            "moderate": "আপনার লক্ষণগুলোতে মনোযোগ দেওয়া দরকার। শীঘ্রই ডাক্তার দেখুন।",
            "normal":   "আপনার লক্ষণগুলো এখন স্বাভাবিক মনে হচ্ছে। পর্যবেক্ষণ করুন।",
        },
    }

    WHEN_TO_SEE = {
        "English": {
            "urgent":   "Go to a doctor or hospital TODAY without delay.",
            "moderate": "See a doctor within the next 2–3 days.",
            "normal":   "Visit an ASHA worker if symptoms persist beyond one week.",
        },
        "Hindi": {
            "urgent":   "आज ही बिना देर किए डॉक्टर या अस्पताल जाएं।",
            "moderate": "अगले 2–3 दिनों में डॉक्टर से मिलें।",
            "normal":   "अगर एक हफ़्ते से ज़्यादा लक्षण रहें तो ASHA वर्कर से मिलें।",
        },
        "Tamil": {
            "urgent":   "இன்றே தாமதிக்காமல் மருத்துவர் அல்லது மருத்துவமனைக்கு செல்லுங்கள்.",
            "moderate": "அடுத்த 2–3 நாட்களில் மருத்துவரை பாருங்கள்.",
            "normal":   "ஒரு வாரத்திற்கு மேல் அறிகுறிகள் இருந்தால் ASHA பணியாளரை சந்தியுங்கள்.",
        },
        "Bengali": {
            "urgent":   "আজই দেরি না করে ডাক্তার বা হাসপাতালে যান।",
            "moderate": "পরের ২–৩ দিনের মধ্যে ডাক্তার দেখুন।",
            "normal":   "এক সপ্তাহের বেশি লক্ষণ থাকলে ASHA কর্মীর কাছে যান।",
        },
    }

    CONDITIONS_MAP = {
        "Unusual bleeding":         ["Cervical issues", "Uterine fibroids", "Hormonal imbalance"],
        "Severe pelvic pain":       ["Endometriosis", "Ovarian cyst", "Pelvic Inflammatory Disease"],
        "Irregular periods":        ["PCOS", "Hormonal imbalance", "Thyroid disorder"],
        "Missed period":            ["Pregnancy", "PCOS", "Stress-related amenorrhea"],
        "Unusual discharge":        ["Infection", "STI", "Cervical issue"],
        "Chest pain / pressure":    ["Cardiac issue", "Acid reflux", "Anxiety"],
        "Shortness of breath":      ["Anaemia", "Cardiac issue", "Respiratory infection"],
        "Severe headache":          ["Hypertension", "Migraine", "Neurological issue"],
        "Swollen legs / ankles":    ["Preeclampsia", "Kidney issue", "Poor circulation"],
        "Pale / yellowing skin":    ["Severe anaemia", "Liver issue", "Nutritional deficiency"],
        "High fever (102°F+)":      ["Infection", "Malaria", "Typhoid"],
        "Severe abdominal pain":    ["Appendicitis", "Gallstones", "Reproductive issue"],
    }

    possible = []
    for sym in english_syms:
        for cond in CONDITIONS_MAP.get(sym, []):
            if cond not in possible:
                possible.append(cond)
    possible = possible[:3]

    lang_recs = RECS.get(language, RECS["English"])
    lang_sum  = SUMMARIES.get(language, SUMMARIES["English"])
    lang_when = WHEN_TO_SEE.get(language, WHEN_TO_SEE["English"])

    ai_data = {
        "summary":            lang_sum[urgency],
        "recommendations":    lang_recs[urgency],
        "possible_conditions": possible,
        "when_to_see_doctor": lang_when[urgency],
    }

    return {
        "urgency":         urgency,
        "red_flags":       red_flags,
        "maternal_alerts": maternal_alerts,
        "ai":              ai_data,
    }

print("✅ Rule-based engine ready — instant, no API needed!")

import gradio as gr

LANGUAGES  = ["English", "Hindi", "Tamil", "Bengali"]
BODY_AREAS = list(SYMPTOMS.keys())

AREA_LABELS = {
    "English": {
        "Head & Brain 🧠":          "🧠 Head",
        "Chest & Heart 🫀":         "🫀 Chest",
        "Abdomen & Stomach 🫃":     "🫃 Abdomen",
        "Pelvis & Reproductive ♀️": "♀️ Pelvis",
        "Legs & Body 🦵":           "🦵 Legs",
        "Skin & General 🌡️":        "🌡️ Skin",
    },
    "Hindi": {
        "Head & Brain 🧠":          "🧠 सिर",
        "Chest & Heart 🫀":         "🫀 सीना",
        "Abdomen & Stomach 🫃":     "🫃 पेट",
        "Pelvis & Reproductive ♀️": "♀️ पेल्विस",
        "Legs & Body 🦵":           "🦵 पैर",
        "Skin & General 🌡️":        "🌡️ त्वचा",
    },
    "Tamil": {
        "Head & Brain 🧠":          "🧠 தலை",
        "Chest & Heart 🫀":         "🫀 மார்பு",
        "Abdomen & Stomach 🫃":     "🫃 வயிறு",
        "Pelvis & Reproductive ♀️": "♀️ இடுப்பு",
        "Legs & Body 🦵":           "🦵 கால்",
        "Skin & General 🌡️":        "🌡️ தோல்",
    },
    "Bengali": {
        "Head & Brain 🧠":          "🧠 মাথা",
        "Chest & Heart 🫀":         "🫀 বুক",
        "Abdomen & Stomach 🫃":     "🫃 পেট",
        "Pelvis & Reproductive ♀️": "♀️ শ্রোণী",
        "Legs & Body 🦵":           "🦵 পা",
        "Skin & General 🌡️":        "🌡️ ত্বক",
    },
}

STEP3_LABEL = {
    "English": "🫀 Where does it hurt?",
    "Hindi":   "🫀 कहाँ दर्द है?",
    "Tamil":   "🫀 வலி எங்கே உள்ளது?",
    "Bengali": "🫀 কোথায় ব্যথা?",
}

def get_choices(area, language):
    data  = SYMPTOMS.get(area, {})
    items = data.get(language, data.get("English", []))
    return [f"{'🔴' if s=='red' else '🟡' if s=='yellow' else '🟢'} {n}" for n, s in items]

def strip_dot(label):
    return label[2:].strip() if label and label[0] in "🔴🟡🟢" else label

def build_svg(language):
    lb = AREA_LABELS.get(language, AREA_LABELS["English"])
    head    = lb["Head & Brain 🧠"]
    chest   = lb["Chest & Heart 🫀"]
    abdomen = lb["Abdomen & Stomach 🫃"]
    pelvis  = lb["Pelvis & Reproductive ♀️"]
    legs    = lb["Legs & Body 🦵"]

    click_head    = "Head &amp; Brain 🧠"
    click_chest   = "Chest &amp; Heart 🫀"
    click_abdomen = "Abdomen &amp; Stomach 🫃"
    click_pelvis  = "Pelvis &amp; Reproductive ♀️"
    click_legs    = "Legs &amp; Body 🦵"

    return f"""
    <div style='background:#1a0033;border-radius:12px;padding:12px;text-align:center;height:100%;'>
      <p style='color:#dda0dd;margin-bottom:6px;font-size:0.85em;'>👇 Click a body area</p>
      <svg viewBox="0 0 200 420" width="170" xmlns="http://www.w3.org/2000/svg" style="display:block;margin:auto;font-family:Arial,sans-serif;">

        <!-- HEAD -->
        <ellipse cx="100" cy="40" rx="28" ry="32" fill="#3d1a5e" stroke="#ff69b4" stroke-width="2"/>
        <ellipse cx="100" cy="18" rx="28" ry="12" fill="#1a0033"/>
        <ellipse cx="74"  cy="30" rx="8"  ry="18" fill="#1a0033"/>
        <ellipse cx="126" cy="30" rx="8"  ry="18" fill="#1a0033"/>
        <circle cx="91"  cy="38" r="3" fill="#ff69b4" opacity="0.7"/>
        <circle cx="109" cy="38" r="3" fill="#ff69b4" opacity="0.7"/>
        <path d="M93 50 Q100 56 107 50" stroke="#ff69b4" stroke-width="1.5" fill="none"/>
        <!-- Head label -->
        <rect x="62" y="28" width="76" height="16" rx="8" fill="rgba(26,0,51,0.85)"/>
        <text x="100" y="40" font-size="10" fill="#ff69b4" text-anchor="middle"
          onclick="document.querySelector('input[value=\'{click_head}\']')?.click()"
          style="cursor:pointer">{head}</text>
        <ellipse cx="100" cy="40" rx="30" ry="34" fill="rgba(255,105,180,0.05)"
          onclick="document.querySelector('input[value=\'{click_head}\']')?.click()"
          style="cursor:pointer"/>

        <!-- NECK -->
        <rect x="91" y="70" width="18" height="16" rx="4" fill="#3d1a5e" stroke="#9370db" stroke-width="1"/>

        <!-- TORSO / CHEST -->
        <rect x="62" y="86" width="76" height="90" rx="14" fill="#2a0044" stroke="#9370db" stroke-width="1.5"/>
        <ellipse cx="85"  cy="106" rx="12" ry="10" fill="#3d1a5e" opacity="0.7"/>
        <ellipse cx="115" cy="106" rx="12" ry="10" fill="#3d1a5e" opacity="0.7"/>
        <text x="96" y="142" font-size="14" fill="#ff69b4">♥</text>
        <!-- Chest label -->
        <rect x="62" y="152" width="76" height="16" rx="8" fill="rgba(26,0,51,0.85)"/>
        <text x="100" y="164" font-size="10" fill="#ff69b4" text-anchor="middle"
          onclick="document.querySelector('input[value=\'{click_chest}\']')?.click()"
          style="cursor:pointer">{chest}</text>
        <rect x="60" y="84" width="80" height="52" rx="10" fill="rgba(255,105,180,0.05)"
          onclick="document.querySelector('input[value=\'{click_chest}\']')?.click()"
          style="cursor:pointer"/>

        <!-- ARMS -->
        <rect x="34"  y="88" width="22" height="72" rx="11" fill="#3d1a5e" stroke="#9370db" stroke-width="1.5"/>
        <rect x="144" y="88" width="22" height="72" rx="11" fill="#3d1a5e" stroke="#9370db" stroke-width="1.5"/>
        <ellipse cx="45"  cy="168" rx="11" ry="9" fill="#2a0044" stroke="#9370db" stroke-width="1"/>
        <ellipse cx="155" cy="168" rx="11" ry="9" fill="#2a0044" stroke="#9370db" stroke-width="1"/>

        <!-- ABDOMEN -->
        <rect x="66" y="174" width="68" height="44" rx="10" fill="#1f0040" stroke="#9370db" stroke-width="1.5"/>
        <circle cx="100" cy="196" r="3" fill="#3d1a5e"/>
        <!-- Abdomen label -->
        <rect x="62" y="186" width="76" height="16" rx="8" fill="rgba(26,0,51,0.85)"/>
        <text x="100" y="198" font-size="10" fill="#ff69b4" text-anchor="middle"
          onclick="document.querySelector('input[value=\'{click_abdomen}\']')?.click()"
          style="cursor:pointer">{abdomen}</text>
        <rect x="64" y="172" width="72" height="48" rx="8" fill="rgba(255,105,180,0.05)"
          onclick="document.querySelector('input[value=\'{click_abdomen}\']')?.click()"
          style="cursor:pointer"/>

        <!-- PELVIS -->
        <ellipse cx="100" cy="238" rx="40" ry="22" fill="#2a0044" stroke="#c86dd7" stroke-width="2"/>
        <!-- Pelvis label -->
        <rect x="62" y="229" width="76" height="16" rx="8" fill="rgba(26,0,51,0.85)"/>
        <text x="100" y="241" font-size="10" fill="#c86dd7" text-anchor="middle"
          onclick="document.querySelector('input[value=\'{click_pelvis}\']')?.click()"
          style="cursor:pointer">{pelvis}</text>
        <ellipse cx="100" cy="238" rx="42" ry="24" fill="rgba(200,109,215,0.05)"
          onclick="document.querySelector('input[value=\'{click_pelvis}\']')?.click()"
          style="cursor:pointer"/>

        <!-- LEGS -->
        <rect x="68"  y="256" width="26" height="100" rx="13" fill="#3d1a5e" stroke="#9370db" stroke-width="1.5"/>
        <rect x="106" y="256" width="26" height="100" rx="13" fill="#3d1a5e" stroke="#9370db" stroke-width="1.5"/>
        <ellipse cx="81"  cy="362" rx="16" ry="8" fill="#2a0044" stroke="#9370db" stroke-width="1"/>
        <ellipse cx="119" cy="362" rx="16" ry="8" fill="#2a0044" stroke="#9370db" stroke-width="1"/>
        <!-- Legs label -->
        <rect x="62" y="298" width="76" height="16" rx="8" fill="rgba(26,0,51,0.85)"/>
        <text x="100" y="310" font-size="10" fill="#ff69b4" text-anchor="middle"
          onclick="document.querySelector('input[value=\'{click_legs}\']')?.click()"
          style="cursor:pointer">{legs}</text>
        <rect x="60" y="254" width="80" height="110" rx="10" fill="rgba(255,105,180,0.05)"
          onclick="document.querySelector('input[value=\'{click_legs}\']')?.click()"
          style="cursor:pointer"/>

      </svg>
      <p style='color:#6a0dad;font-size:0.75em;margin-top:4px;'>Tap figure or select →</p>
    </div>"""

def build_area_radio(language, area):
    label = STEP3_LABEL.get(language, STEP3_LABEL["English"])
    return gr.Radio(choices=BODY_AREAS, value=area, label=label)

def update_all(language, area):
    s = UI_STRINGS.get(language, UI_STRINGS["English"])
    choices = get_choices(area, language)
    return (
        gr.Radio(choices=[s["yes"], s["no"]], value=s["no"], label=s["step2"]),
        gr.HTML(value=build_svg(language)),
        build_area_radio(language, area),
        gr.CheckboxGroup(choices=choices, value=[], label=s["step4"]),
        gr.Textbox(placeholder=s["placeholder"], label=s.get("step5","✍️"), lines=2),
        gr.Button(s["btn"]),
    )

def update_symptoms(area, language):
    s = UI_STRINGS.get(language, UI_STRINGS["English"])
    return gr.CheckboxGroup(
        choices=get_choices(area, language), value=[],
        label=s["step4"]
    )

def analyze(language, pregnant_val, area, selections, free_text):
    s = UI_STRINGS.get(language, UI_STRINGS["English"])
    is_pregnant = pregnant_val == s["yes"]
    clean = [strip_dot(x) for x in (selections or [])]
    if not clean and not (free_text and free_text.strip()):
        return f"<div style='background:#0d0020;border-radius:16px;padding:30px;text-align:center;'><p style='color:#9370db;font-size:1.1em;'>{s['waiting']}</p></div>"
    report = generate_health_report(language, is_pregnant, area, clean, free_text)
    return render_report(report, language)

# ── BUILD UI ──────────────────────────────────────────────

with gr.Blocks(theme=gr.themes.Base(), css="""
    body, .gradio-container { background:#0d0020 !important; }
    label { color:#dda0dd !important; }
    .gr-button { font-size:1.1em !important; }
""") as demo:

    # Header
    gr.HTML("""
    <div style='background:linear-gradient(135deg,#1a0033,#3d0066);
                border-radius:16px;padding:20px;text-align:center;margin-bottom:10px;'>
      <h1 style='color:#ff69b4;font-size:2.2em;margin:0;'>🌸 SakhiAI</h1>
      <p style='color:#dda0dd;margin:3px 0;'>Her First Doctor</p>
      <p style='color:#c8a0e8;font-size:0.82em;font-style:italic;'>
        Every woman deserves a friend who knows health.
      </p>
    </div>""")

    # Language picker
    lang = gr.Dropdown(
        choices=LANGUAGES, value="Hindi",
        label="🌐 Language / भाषा / மொழி / ভাষা"
    )

    # Pregnant question
    pregnant = gr.Radio(
        choices=[UI_STRINGS["Hindi"]["yes"], UI_STRINGS["Hindi"]["no"]],
        value=UI_STRINGS["Hindi"]["no"],
        label=UI_STRINGS["Hindi"]["step2"]
    )

    # ── Side by side: diagram LEFT, area selector RIGHT ──
    with gr.Row():
        with gr.Column(scale=1, min_width=200):
            body_diagram = gr.HTML(value=build_svg("Hindi"))

        with gr.Column(scale=2):
            area = gr.Radio(
                choices=BODY_AREAS,
                value="Pelvis & Reproductive ♀️",
                label=STEP3_LABEL["Hindi"]
            )
            symptoms_box = gr.CheckboxGroup(
                choices=get_choices("Pelvis & Reproductive ♀️", "Hindi"),
                value=[],
                label=UI_STRINGS["Hindi"]["step4"]
            )

    # Free text
    free_text = gr.Textbox(
        placeholder=UI_STRINGS["Hindi"]["placeholder"],
        label=UI_STRINGS["Hindi"].get("step5", "✍️ अपने शब्दों में बताएं"),
        lines=2
    )

    btn = gr.Button(UI_STRINGS["Hindi"]["btn"], variant="primary", size="lg")

    out = gr.HTML(value="""
    <div style='background:#0d0020;border-radius:16px;padding:30px;text-align:center;'>
      <p style='color:#9370db;font-size:1.1em;'>
        🌸 Sakhi is waiting…<br>
        <span style='color:#6a0dad;font-size:0.9em;'>Select your symptoms and click Ask Sakhi</span>
      </p>
    </div>""")

    # ── Interactions ──────────────────────────────────────
    lang.change(
        fn=update_all,
        inputs=[lang, area],
        outputs=[pregnant, body_diagram, area, symptoms_box, free_text, btn]
    )
    area.change(
        fn=update_symptoms,
        inputs=[area, lang],
        outputs=symptoms_box
    )
    btn.click(
        fn=analyze,
        inputs=[lang, pregnant, area, symptoms_box, free_text],
        outputs=out
    )

demo.launch(share=True, debug=False)