# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAEhMjghEjWItmmPumr0sKHNAGWchWIy

## Our Solution
SakhiAI is an AI-powered health companion for every Indian woman.  
It understands symptoms in **plain language**, detects **red flags using ML**,  
translates reports into **Indian languages using neural AI**,  
and generates **personalized recommendations using an LLM** — all for free.

## AI/ML Stack
| Component | Model | Purpose |
|-----------|-------|---------|
| Symptom Extraction | `facebook/bart-large-mnli` | Understand free-text symptoms |
| Severity Classification | `cross-encoder/nli-deberta-v3-small` | Predict urgency level |
| Translation | `Helsinki-NLP/opus-mt-en-hi` | Hindi/Tamil/Bengali reports |
| Recommendations | `google/flan-t5-base` | LLM-generated health advice |
| Bias Detection | `d4data/bias-detection-model` | Audit report for gender bias |
"""

!pip install transformers -q
!pip install sentencepiece -q
!pip install torch -q
!pip install gradio -q
!pip install accelerate -q

print("All packages installed!")

from transformers import (
    pipeline,
    MarianMTModel,
    MarianTokenizer,
    T5ForConditionalGeneration,
    T5Tokenizer,
)
import torch

print("⏳ Loading AI models — please wait...\n")

# ── Model 1: Zero-shot severity classifier
print("  [1/4] Loading severity classifier (DeBERTa)...", end=" ")
severity_classifier = pipeline(
    "zero-shot-classification",
    model="cross-encoder/nli-deberta-v3-small",
    device=-1
)
print("✅")

# ── Model 2: Symptom extractor (BART)
print("  [2/4] Loading symptom extractor (BART)...", end=" ")
symptom_extractor = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli",
    device=-1
)
print("✅")

# ── Model 3: Recommendation LLM (Flan-T5)
# Fix: load T5 directly instead of via pipeline
print("  [3/4] Loading recommendation LLM (Flan-T5)...", end=" ")
t5_tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-base")
t5_model     = T5ForConditionalGeneration.from_pretrained("google/flan-t5-base")
print("✅")

# ── Model 4: Hindi translation
print("  [4/4] Loading Hindi translation model...", end=" ")
hi_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-hi")
hi_model     = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-en-hi")
print("✅")

# ── Helper: generate text with Flan-T5
def ask_flan(prompt, max_tokens=200):
    inputs  = t5_tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
    outputs = t5_model.generate(**inputs, max_new_tokens=max_tokens)
    return t5_tokenizer.decode(outputs[0], skip_special_tokens=True)

print("\n🌸 All 4 AI models loaded and ready!")
print(f"   Running on: {'GPU ⚡' if torch.cuda.is_available() else 'CPU (free tier)'}")

import kagglehub

# Download latest version
path = kagglehub.dataset_download("csafrit2/maternal-health-risk-data")

print("Path to dataset files:", path)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("prasoonkottarathil/polycystic-ovary-syndrome-pcos")

print("Path to dataset files:", path)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("itachi9604/disease-symptom-description-dataset")

print("Path to dataset files:", path)

import pandas as pd
import os

# ── Load Maternal Health Risk
maternal_path = "/root/.cache/kagglehub/datasets/csafrit2/maternal-health-risk-data/versions/1"
maternal_file = [f for f in os.listdir(maternal_path) if f.endswith(".csv")][0]
maternal_df   = pd.read_csv(os.path.join(maternal_path, maternal_file))
maternal_df.columns = [c.strip().lower().replace(" ","_") for c in maternal_df.columns]
print(f"✅ Maternal Health: {maternal_df.shape[0]} rows")
print(f"   Columns: {list(maternal_df.columns)}")
print(f"   Risk distribution:\n{maternal_df.iloc[:,-1].value_counts()}\n")

# ── Load PCOS Dataset
pcos_path = "/root/.cache/kagglehub/datasets/prasoonkottarathil/polycystic-ovary-syndrome-pcos/versions/3"
pcos_files = [f for f in os.listdir(pcos_path) if f.endswith(".csv")]
print(f"   PCOS files found: {pcos_files}")
pcos_df    = pd.read_csv(os.path.join(pcos_path, pcos_files[0]))
pcos_df.columns = [c.strip().lower().replace(" ","_") for c in pcos_df.columns]
print(f"✅ PCOS: {pcos_df.shape[0]} rows")
print(f"   Columns: {list(pcos_df.columns[:8])}...\n")

# ── Load Symptom-Disease Dataset
symptom_path  = "/kaggle/input/disease-symptom-description-dataset"

# fallback — kagglehub cache
if not os.path.exists(symptom_path):
    symptom_path = "/root/.cache/kagglehub/datasets/itachi9604/disease-symptom-description-dataset"
    for root, dirs, files in os.walk(symptom_path):
        for f in files:
            if f.endswith(".csv"):
                symptom_path = root
                break

symptom_files = [f for f in os.listdir(symptom_path) if f.endswith(".csv")]
print(f"   Symptom files found: {symptom_files}")

# Load the main dataset file
symptom_df = pd.read_csv(os.path.join(symptom_path, symptom_files[0]))
symptom_df.columns = [c.strip().lower().replace(" ","_") for c in symptom_df.columns]
print(f"✅ Symptom-Disease: {symptom_df.shape[0]} rows")
print(f"   Columns: {list(symptom_df.columns[:6])}...\n")

import numpy as np

# ── Load the remaining symptom files

# Main disease-symptom mapping
disease_symptom_df = pd.read_csv(os.path.join(symptom_path, "dataset.csv"))
disease_symptom_df.columns = [c.strip().lower().replace(" ","_")
                               for c in disease_symptom_df.columns]
print(f"✅ Disease-Symptom map: {disease_symptom_df.shape[0]} rows")
print(f"   Columns: {list(disease_symptom_df.columns[:6])}...\n")

# Symptom severity scores
severity_df = pd.read_csv(os.path.join(symptom_path, "Symptom-severity.csv"))
severity_df.columns = [c.strip().lower().replace(" ","_")
                        for c in severity_df.columns]
print(f"✅ Symptom Severity: {severity_df.shape[0]} symptoms with scores")
print(f"   Columns: {list(severity_df.columns)}\n")

# Symptom precautions
precaution_df = pd.read_csv(os.path.join(symptom_path, "symptom_precaution.csv"))
precaution_df.columns = [c.strip().lower().replace(" ","_")
                          for c in precaution_df.columns]
print(f"✅ Precautions: {precaution_df.shape[0]} diseases with advice")
print(f"   Columns: {list(precaution_df.columns)}\n")

symptom_severity_map = {}
for _, row in severity_df.iterrows():
    symptom = str(row.iloc[0]).strip().lower().replace(" ", "_")
    weight  = row.iloc[1]
    symptom_severity_map[symptom] = weight

print(f"✅ Severity map built: {len(symptom_severity_map)} symptoms scored")

# ── 1. Maternal Risk Predictor

def predict_maternal_risk(age, systolic_bp, diastolic_bp,
                           blood_glucose, body_temp, heart_rate):
    """
    Nearest-neighbor search on real Kaggle maternal dataset.
    Returns risk level + confidence.
    """
    user_vector = np.array([
        age, systolic_bp, diastolic_bp,
        blood_glucose, body_temp, heart_rate
    ], dtype=float)

    features = maternal_df[['age','systolicbp','diastolicbp',
                             'bs','bodytemp','heartrate']].values.astype(float)

    # Normalize
    col_max     = features.max(axis=0) + 1e-8
    norm_feat   = features / col_max
    norm_user   = user_vector / col_max

    # Find 10 nearest neighbors
    distances   = np.linalg.norm(norm_feat - norm_user, axis=1)
    top_k_idx   = distances.argsort()[:10]
    top_k_risks = maternal_df.iloc[top_k_idx]['risklevel'].values

    # Majority vote
    unique, counts  = np.unique(top_k_risks, return_counts=True)
    predicted_risk  = unique[counts.argmax()]
    confidence      = counts.max() / 10

    return predicted_risk, confidence


# ── 2. Disease Matcher

def match_disease_from_symptoms(user_symptoms):
    """
    Searches disease-symptom dataset for matching conditions.
    Returns top 3 with match scores.
    """
    matched = []

    for _, row in disease_symptom_df.iterrows():
        disease   = row.iloc[0]
        row_text  = " ".join(
            str(v).lower().replace("_"," ")
            for v in row.values
        )
        score = sum(
            1 for s in user_symptoms
            if s.lower().replace("_"," ") in row_text
        )
        if score > 0:
            matched.append((disease, score))

    matched.sort(key=lambda x: x[1], reverse=True)
    return matched[:3]


# ── 3. Severity Score Calculator

def calculate_severity_score(user_symptoms):
    """
    Uses real Symptom-severity.csv weights to
    calculate total severity score (0-100).
    """
    total = 0
    max_possible = 7 * len(user_symptoms)  # max weight is 7

    for symptom in user_symptoms:
        clean = symptom.lower().replace(" ","_")
        weight = symptom_severity_map.get(clean, 3)  # default weight 3
        total += weight

    score = min((total / max(max_possible, 1)) * 100, 100)
    return round(score, 1)


# ── 4. Precaution Fetcher

def get_precautions(disease_name):
    """
    Fetches real precautions from dataset for a disease.
    """
    match = precaution_df[
        precaution_df.iloc[:,0].str.lower() == disease_name.lower()
    ]
    if match.empty:
        return []

    precautions = []
    for col in match.columns[1:]:
        val = str(match.iloc[0][col]).strip()
        if val and val.lower() not in ["nan", "none", ""]:
            precautions.append(val)
    return precautions


# ── 5. PCOS Risk Screener

def screen_pcos_risk(user_symptoms):
    """
    Flags potential PCOS based on symptom patterns.
    """
    pcos_symptoms = [
        "irregular periods", "missed period",
        "unusual bleeding", "unusual discharge",
        "pain during intercourse", "weight gain",
        "fatigue or tiredness", "severe pelvic pain"
    ]
    matches    = [s for s in user_symptoms if s in pcos_symptoms]
    risk_score = len(matches) / len(pcos_symptoms)
    return matches, round(risk_score * 100, 1)


# ── Test everything ───────────────────────────────────────

print("\n Testing Full Dataset Engine...\n")

# Test 1: Maternal risk
risk, conf = predict_maternal_risk(
    age=28, systolic_bp=130, diastolic_bp=85,
    blood_glucose=15, body_temp=98.6, heart_rate=86
)
print(f"  Maternal Risk:  {risk.upper()}  ({conf:.0%} confidence)")

# Test 2: Disease matcher
test_symptoms = ["irregular periods", "unusual bleeding", "fatigue or tiredness"]
diseases = match_disease_from_symptoms(test_symptoms)
print(f"\n  🔍 Disease Matches for {test_symptoms}:")
for disease, score in diseases:
    precautions = get_precautions(disease)
    print(f"     → {disease}  ({score} matches)")
    if precautions:
        print(f"        Precaution: {precautions[0]}")

# Test 3: Severity score
score = calculate_severity_score(test_symptoms)
print(f"\n  📊 Severity Score:  {score}/100")

# Test 4: PCOS screen
matches, pcos_risk = screen_pcos_risk(test_symptoms)
print(f"\n  PCOS Risk:  {pcos_risk}%")
print(f"     Indicators: {matches}")

print("\n Full dataset engine ready!")

# ── ALL_SYMPTOMS list ─────────────────────────────────────
ALL_SYMPTOMS = [
    # Head
    "severe headache", "blurred vision", "dizziness or fainting",
    "mild headache", "forgetfulness",
    # Chest
    "chest pain or pressure", "shortness of breath",
    "heart palpitations", "mild chest tightness", "fatigue or tiredness",
    # Abdomen
    "severe abdominal pain", "persistent vomiting",
    "bloating or gas", "loss of appetite", "nausea",
    # Pelvis
    "unusual bleeding", "severe pelvic pain", "irregular periods",
    "unusual discharge", "pain during intercourse", "missed period",
    # Legs
    "swollen legs or ankles", "severe joint pain",
    "mild body ache", "numbness or tingling", "weakness",
    # Skin/General
    "high fever", "unexplained weight loss",
    "skin rash or itching", "pale or yellowing skin", "mild fatigue",
]

# ── RED FLAG MAP ──────────────────────────────────────────
RED_FLAG_MAP = {
    "unusual bleeding":
        "Could indicate cervical or uterine issues. Early screening is critical.",
    "severe pelvic pain":
        "May indicate endometriosis, ovarian cyst, or ectopic pregnancy.",
    "chest pain or pressure":
        "Women's heart attack symptoms are often dismissed. Do not ignore.",
    "severe headache":
        "Could indicate high blood pressure or neurological issue.",
    "blurred vision":
        "May indicate hypertension or gestational complications.",
    "severe abdominal pain":
        "Could indicate appendicitis, gallstones, or reproductive issue.",
    "swollen legs or ankles":
        "Possible sign of preeclampsia if pregnant, or heart/kidney issue.",
    "pale or yellowing skin":
        "May indicate severe anemia — very common and dangerous in women.",
    "high fever":
        "Needs immediate attention — could be infection or severe illness.",
}

# ── MATERNAL WARNINGS ─────────────────────────────────────
MATERNAL_WARNINGS = {
    "unusual bleeding":
        "⚠️ Bleeding during pregnancy is always serious. Go to hospital NOW.",
    "severe pelvic pain":
        "⚠️ Could indicate miscarriage or ectopic pregnancy. Emergency care needed.",
    "swollen legs or ankles":
        "⚠️ Sign of preeclampsia — dangerous in pregnancy. See doctor today.",
    "severe headache":
        "⚠️ Headache + pregnancy = possible preeclampsia. Do not wait.",
    "blurred vision":
        "⚠️ Vision changes in pregnancy need immediate evaluation.",
}

print("✅ ALL_SYMPTOMS, RED_FLAG_MAP, MATERNAL_WARNINGS loaded!")
print(f"   {len(ALL_SYMPTOMS)} symptoms | {len(RED_FLAG_MAP)} red flags | {len(MATERNAL_WARNINGS)} maternal warnings")

from transformers import MarianMTModel, MarianTokenizer

# ── Load Hindi translation model ──────────────────────────
print("⏳ Loading Hindi translation model...", end=" ")
hi_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-hi")
hi_model     = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-en-hi")
print("✅")

# ── Translation function ──────────────────────────────────
def translate_text(text, target_lang):
    """Translate English text to target language."""

    if target_lang == "English":
        return text

    if target_lang == "Hindi":
        tokenizer = hi_tokenizer
        model     = hi_model
    else:
        # For other languages return English for now
        return text

    # Split into sentences
    sentences = [s.strip() for s in text.split(".") if s.strip()]
    if not sentences:
        return text

    translated = []
    for sentence in sentences:
        inputs  = tokenizer(
            [sentence],
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=256
        )
        outputs = model.generate(**inputs)
        result  = tokenizer.decode(outputs[0], skip_special_tokens=True)
        translated.append(result)

    return ". ".join(translated)

# ── Quick test ────────────────────────────────────────────
test = translate_text("Please visit your nearest doctor immediately.", "Hindi")
print(f"\n🧪 Translation test:")
print(f"   EN: Please visit your nearest doctor immediately.")
print(f"   HI: {test}")
print("\n✅ translate_text ready!")

def run_sakhai_pipeline(user_input, language, is_pregnant,
                         age=25, systolic_bp=120, diastolic_bp=80,
                         blood_glucose=10, body_temp=98.6, heart_rate=80):
    """
    Full SakhiAI pipeline:
    1. NLP extracts symptoms from free text
    2. Dataset engine matches diseases + severity
    3. Maternal risk predicted from real data
    4. Flan-T5 generates personalized recommendations
    5. Report translated to chosen language
    """

    print("="*55)
    print(" SakhiAI — Running Full AI Pipeline")
    print("="*55)

    # ── STEP 1: NLP Symptom Extraction ───────────────────
    print("\n⏳ Step 1: Extracting symptoms from text...")
    bart_result = symptom_extractor(
        user_input,
        candidate_labels=ALL_SYMPTOMS,
        multi_label=True,
    )
    extracted = [
        label for label, score
        in zip(bart_result["labels"], bart_result["scores"])
        if score > 0.15
    ][:5]
    print(f"   ✅ Extracted: {extracted}")

    # ── STEP 2: Severity Score from Dataset ──────────────
    print("\n⏳ Step 2: Calculating severity from dataset...")
    severity_score = calculate_severity_score(extracted)
    if severity_score >= 60:
        urgency = "HIGH"
        urgency_color = "🔴"
    elif severity_score >= 35:
        urgency = "MODERATE"
        urgency_color = "🟡"
    else:
        urgency = "LOW"
        urgency_color = "🟢"
    print(f"   ✅ Severity Score: {severity_score}/100 → {urgency_color} {urgency}")

    # ── STEP 3: Disease Matching ──────────────────────────
    print("\n⏳ Step 3: Matching diseases from dataset...")
    matched_diseases = match_disease_from_symptoms(extracted)
    print(f"   ✅ Top match: {matched_diseases[0][0] if matched_diseases else 'None'}")

    # ── STEP 4: Red Flag Detection ────────────────────────
    print("\n⏳ Step 4: Checking red flags...")
    red_flags = [
        (s, RED_FLAG_MAP[s])
        for s in extracted
        if s in RED_FLAG_MAP
    ]
    maternal_alerts = [
        (s, MATERNAL_WARNINGS[s])
        for s in extracted
        if is_pregnant and s in MATERNAL_WARNINGS
    ]
    print(f"   ✅ Red flags: {len(red_flags)} | Maternal alerts: {len(maternal_alerts)}")

    # ── STEP 5: Maternal Risk from Dataset ───────────────
    print("\n⏳ Step 5: Predicting maternal risk from dataset...")
    maternal_risk, maternal_conf = predict_maternal_risk(
        age, systolic_bp, diastolic_bp,
        blood_glucose, body_temp, heart_rate
    )
    print(f"   ✅ Maternal risk: {maternal_risk} ({maternal_conf:.0%} confidence)")

    # ── STEP 6: PCOS Screening ────────────────────────────
    print("\n⏳ Step 6: PCOS screening...")
    pcos_matches, pcos_risk = screen_pcos_risk(extracted)
    print(f"   ✅ PCOS risk: {pcos_risk}%")

    # ── STEP 7: LLM Recommendations (Flan-T5) ────────────
    print("\n⏳ Step 7: Generating recommendations with Flan-T5...")
    top_disease = matched_diseases[0][0] if matched_diseases else "unknown condition"
    precautions = get_precautions(top_disease)

    flan_prompt = f"""
    A woman has these symptoms: {', '.join(extracted)}.
    Severity is {urgency}. {'She is pregnant.' if is_pregnant else ''}
    Possible condition: {top_disease}.
    What are 3 simple health recommendations for her?
    """
    flan_response = ask_flan(flan_prompt, max_tokens=150)
    print(f"   ✅ Recommendations generated")

    # ── STEP 8: Translation ───────────────────────────────
    translated_urgency = urgency
    translated_flan    = flan_response
    if language == "Hindi":
        print("\n⏳ Step 8: Translating to Hindi...")
        translated_urgency = translate_text(
            f"Urgency level is {urgency}. Please seek medical care.", "Hindi"
        )
        translated_flan = translate_text(flan_response, "Hindi")
        print(f"   ✅ Translation done")
    else:
        print(f"\n⏳ Step 8: Language is {language} — no translation needed")

    # ── BUILD FINAL REPORT ────────────────────────────────
    print("\n" + "="*55)
    print("📋 GENERATING FINAL REPORT...")
    print("="*55)

    report = {
        "language":        language,
        "is_pregnant":     is_pregnant,
        "extracted":       extracted,
        "severity_score":  severity_score,
        "urgency":         urgency,
        "red_flags":       red_flags,
        "maternal_alerts": maternal_alerts,
        "maternal_risk":   maternal_risk,
        "maternal_conf":   maternal_conf,
        "diseases":        matched_diseases,
        "precautions":     precautions,
        "pcos_risk":       pcos_risk,
        "flan_recs":       flan_response,
        "translated_recs": translated_flan,
    }

    return report


# ── Test the full pipeline ────────────────────────────────

test_report = run_sakhai_pipeline(
    user_input   = "mera pet mein dard hai aur periods nahi aa rahe",
    language     = "Hindi",
    is_pregnant  = False,
    age          = 26,
    systolic_bp  = 125,
    diastolic_bp = 82,
    blood_glucose= 12,
    body_temp    = 98.6,
    heart_rate   = 78,
)

def get_translated_report_text(urgency, diseases, recs, lang):

    # ── English ───────────────────────────────────────────
    english = {
        "urgent":     "🚨 URGENT: These symptoms need immediate medical attention!",
        "moderate":   "⚡ ATTENTION: Please consult a doctor within 2-3 days.",
        "normal":     "✅ Your symptoms seem manageable. Keep tracking daily.",
        "see_doctor": "Show this report to your nearest ASHA worker or doctor.",
        "screening":  "Get these screenings done regularly:",
        "recs_title": "Recommendations for you:",
        "pregnant":   "You are pregnant. Extra care is needed.",
        "pcos_risk":  "You may be at risk for PCOS. Please consult a doctor.",
        "area":       "Body Area",
        "symptoms":   "Symptoms Detected",
        "conditions": "Possible Conditions",
        "maternal":   "Pregnancy Alert",
    }

    # ── Hindi (Devanagari) ────────────────────────────────
    hindi = {
        "urgent":     "🚨 ज़रूरी: इन लक्षणों पर तुरंत डॉक्टर से मिलें!",
        "moderate":   "⚡ ध्यान दें: 2-3 दिन में डॉक्टर से ज़रूर मिलें।",
        "normal":     "✅ आपके लक्षण अभी सामान्य हैं। रोज़ ट्रैक करते रहें।",
        "see_doctor": "यह रिपोर्ट अपनी नज़दीकी ASHA वर्कर या डॉक्टर को दिखाएं।",
        "screening":  "ये जाँच ज़रूर करवाएं:",
        "recs_title": "आपके लिए सलाह:",
        "pregnant":   "आप गर्भवती हैं। अतिरिक्त देखभाल ज़रूरी है।",
        "pcos_risk":  "आपको PCOS का खतरा हो सकता है। डॉक्टर से मिलें।",
        "area":       "शरीर का हिस्सा",
        "symptoms":   "पहचाने गए लक्षण",
        "conditions": "संभावित बीमारियाँ",
        "maternal":   "गर्भावस्था चेतावनी",
    }

    # ── Tamil (Tamil script) ──────────────────────────────
    tamil = {
        "urgent":     "🚨 அவசரம்: இந்த அறிகுறிகளுக்கு உடனடி மருத்துவ கவனம் தேவை!",
        "moderate":   "⚡ கவனம்: 2-3 நாட்களில் மருத்துவரை சந்தியுங்கள்।",
        "normal":     "✅ உங்கள் அறிகுறிகள் இப்போது சாதாரணமானவை। தினமும் கவனியுங்கள்।",
        "see_doctor": "இந்த அறிக்கையை உங்கள் ASHA பணியாளர் அல்லது மருத்துவரிடம் காட்டுங்கள்।",
        "screening":  "இந்த பரிசோதனைகளை செய்யுங்கள்:",
        "recs_title": "உங்களுக்கான ஆலோசனை:",
        "pregnant":   "நீங்கள் கர்ப்பமாக இருக்கிறீர்கள். கூடுதல் கவனிப்பு தேவை।",
        "pcos_risk":  "உங்களுக்கு PCOS அபாயம் இருக்கலாம். மருத்துவரை சந்தியுங்கள்।",
        "area":       "உடல் பகுதி",
        "symptoms":   "கண்டறியப்பட்ட அறிகுறிகள்",
        "conditions": "சாத்தியமான நோய்கள்",
        "maternal":   "கர்ப்பகால எச்சரிக்கை",
    }

    # ── Bengali (Bengali script) ──────────────────────────
    bengali = {
        "urgent":     "🚨 জরুরি: এই লক্ষণগুলোর জন্য তাৎক্ষণিক চিকিৎসা প্রয়োজন!",
        "moderate":   "⚡ মনোযোগ: ২-৩ দিনের মধ্যে ডাক্তার দেখুন।",
        "normal":     "✅ আপনার লক্ষণগুলো এখন নিয়ন্ত্রণযোগ্য। প্রতিদিন ট্র্যাক করুন।",
        "see_doctor": "এই রিপোর্ট আপনার নিকটস্থ ASHA কর্মী বা ডাক্তারকে দেখান।",
        "screening":  "এই পরীক্ষাগুলো নিয়মিত করুন:",
        "recs_title": "আপনার জন্য পরামর্শ:",
        "pregnant":   "আপনি গর্ভবতী। বিশেষ যত্ন নেওয়া দরকার।",
        "pcos_risk":  "আপনার PCOS এর ঝুঁকি থাকতে পারে। ডাক্তার দেখুন।",
        "area":       "শরীরের অংশ",
        "symptoms":   "শনাক্ত লক্ষণসমূহ",
        "conditions": "সম্ভাব্য রোগসমূহ",
        "maternal":   "গর্ভাবস্থা সতর্কতা",
    }

    # ── Telugu (Telugu script) ────────────────────────────
    telugu = {
        "urgent":     "🚨 అత్యవసరం: ఈ లక్షణాలకు వెంటనే వైద్య సహాయం పొందండి!",
        "moderate":   "⚡ శ్రద్ధ: 2-3 రోజులలో డాక్టర్‌ను సంప్రదించండి।",
        "normal":     "✅ మీ లక్షణాలు ఇప్పుడు సాధారణంగా ఉన్నాయి. రోజూ ట్రాక్ చేయండి।",
        "see_doctor": "ఈ నివేదికను మీ సమీప ASHA కార్యకర్త లేదా డాక్టర్‌కు చూపించండి।",
        "screening":  "ఈ పరీక్షలు క్రమం తప్పకుండా చేయండి:",
        "recs_title": "మీకు సూచనలు:",
        "pregnant":   "మీరు గర్భవతి. అదనపు జాగ్రత్త అవసరం.",
        "pcos_risk":  "మీకు PCOS ప్రమాదం ఉండవచ్చు. డాక్టర్‌ను సంప్రదించండి.",
        "area":       "శరీర భాగం",
        "symptoms":   "గుర్తించిన లక్షణాలు",
        "conditions": "సాధ్యమయ్యే వ్యాధులు",
        "maternal":   "గర్భధారణ హెచ్చరిక",
    }

    # ── Marathi (Devanagari) ──────────────────────────────
    marathi = {
        "urgent":     "🚨 तातडीचे: या लक्षणांसाठी तत्काळ वैद्यकीय मदत घ्या!",
        "moderate":   "⚡ लक्ष द्या: 2-3 दिवसांत डॉक्टरांना भेटा।",
        "normal":     "✅ तुमची लक्षणे आत्ता सामान्य आहेत. रोज ट्रॅक करत राहा।",
        "see_doctor": "हा अहवाल तुमच्या जवळच्या ASHA कार्यकर्त्याला किंवा डॉक्टरांना दाखवा।",
        "screening":  "हे तपासण्या नियमित करा:",
        "recs_title": "तुमच्यासाठी सल्ला:",
        "pregnant":   "तुम्ही गर्भवती आहात. अतिरिक्त काळजी घ्या.",
        "pcos_risk":  "तुम्हाला PCOS चा धोका असू शकतो. डॉक्टरांना भेटा.",
        "area":       "शरीराचा भाग",
        "symptoms":   "ओळखलेली लक्षणे",
        "conditions": "संभाव्य आजार",
        "maternal":   "गर्भावस्था इशारा",
    }

    # ── Gujarati (Gujarati script) ────────────────────────
    gujarati = {
        "urgent":     "🚨 તાકીદનું: આ લક્ષણો માટે તરત જ ડૉક્ટરને મળો!",
        "moderate":   "⚡ ધ્યાન આપો: 2-3 દિવસમાં ડૉક્ટરને મળો।",
        "normal":     "✅ તમારાં લક્ષણો અત્યારે સામાન્ય છે. રોજ ટ્રૅક કરો।",
        "see_doctor": "આ રિપોર્ટ તમારી નજીકની ASHA વર્કર અથવા ડૉક્ટરને બતાવો।",
        "screening":  "આ તપાસ નિયમિત કરાવો:",
        "recs_title": "તમારા માટે સલાહ:",
        "pregnant":   "તમે ગર્ભવતી છો. વધારાની કાળજી જરૂરી છે.",
        "pcos_risk":  "તમને PCOS નો ખતરો હોઈ શકે. ડૉક્ટરને મળો.",
        "area":       "શરીરનો ભાગ",
        "symptoms":   "ઓળખાયેલાં લક્ષણો",
        "conditions": "સંભવિત બીમારીઓ",
        "maternal":   "ગર્ભાવસ્થા ચેતવણી",
    }

    lang_map = {
        "English":  english,
        "Hindi":    hindi,
        "Tamil":    tamil,
        "Bengali":  bengali,
        "Telugu":   telugu,
        "Marathi":  marathi,
        "Gujarati": gujarati,
    }

    chosen = lang_map.get(lang, english)

    # AI translate recommendations if Hindi
    if lang == "Hindi" and recs:
        translated_recs = translate_text(recs, "Hindi")
    else:
        translated_recs = recs

    return chosen, translated_recs


# ── Test ──────────────────────────────────────────────────
print("🧪 Testing native language strings...\n")
for lang in ["English", "Hindi", "Tamil", "Bengali", "Telugu", "Marathi", "Gujarati"]:
    s, _ = get_translated_report_text("HIGH", [], "", lang)
    print(f"  {lang}:")
    print(f"    {s['urgent']}")
    print(f"    {s['see_doctor']}\n")

print("✅ 7 languages in native script ready!")

# ── Symptoms in native languages ─────────────────────────

SYMPTOMS_TRANSLATED = {
    "Head & Brain": {
        "English": [
            ("Severe headache",       "red"),
            ("Blurred vision",        "red"),
            ("Dizziness / fainting",  "yellow"),
            ("Mild headache",         "green"),
            ("Forgetfulness",         "green"),
        ],
        "Hindi": [
            ("तेज़ सिरदर्द",           "red"),
            ("धुंधला दिखना",           "red"),
            ("चक्कर आना / बेहोशी",     "yellow"),
            ("हल्का सिरदर्द",          "green"),
            ("भूलना",                  "green"),
        ],
        "Tamil": [
            ("கடுமையான தலைவலி",        "red"),
            ("மங்கலான பார்வை",         "red"),
            ("தலைசுற்றல் / மயக்கம்",   "yellow"),
            ("லேசான தலைவலி",           "green"),
            ("மறதி",                   "green"),
        ],
        "Bengali": [
            ("তীব্র মাথাব্যথা",          "red"),
            ("ঝাপসা দৃষ্টি",             "red"),
            ("মাথা ঘোরা / অজ্ঞান",      "yellow"),
            ("হালকা মাথাব্যথা",          "green"),
            ("ভুলে যাওয়া",              "green"),
        ],
        "Telugu": [
            ("తీవ్రమైన తలనొప్పి",        "red"),
            ("మసకబారిన దృష్టి",          "red"),
            ("తలతిరగడం / మూర్ఛ",        "yellow"),
            ("తేలికపాటి తలనొప్పి",       "green"),
            ("మరచిపోవడం",               "green"),
        ],
        "Marathi": [
            ("तीव्र डोकेदुखी",            "red"),
            ("अंधुक दिसणे",              "red"),
            ("चक्कर येणे / बेशुद्धी",     "yellow"),
            ("सौम्य डोकेदुखी",           "green"),
            ("विसरणे",                   "green"),
        ],
        "Gujarati": [
            ("તીવ્ર માથાનો દુખાવો",       "red"),
            ("ઝાંખું દેખાવું",            "red"),
            ("ચક્કર આવવા / બેહોશી",      "yellow"),
            ("હળવો માથાનો દુખાવો",        "green"),
            ("ભૂલી જવું",                "green"),
        ],
    },

    "Chest & Heart": {
        "English": [
            ("Chest pain or pressure",  "red"),
            ("Shortness of breath",     "red"),
            ("Heart palpitations",      "yellow"),
            ("Mild chest tightness",    "yellow"),
            ("Fatigue / tiredness",     "green"),
        ],
        "Hindi": [
            ("सीने में दर्द या दबाव",    "red"),
            ("सांस लेने में तकलीफ",      "red"),
            ("दिल की धड़कन तेज़ होना",   "yellow"),
            ("सीने में हल्की जकड़न",     "yellow"),
            ("थकान",                    "green"),
        ],
        "Tamil": [
            ("மார்பு வலி அல்லது அழுத்தம்", "red"),
            ("மூச்சு திணறல்",            "red"),
            ("இதய படபடப்பு",             "yellow"),
            ("லேசான மார்பு இறுக்கம்",    "yellow"),
            ("சோர்வு",                   "green"),
        ],
        "Bengali": [
            ("বুকে ব্যথা বা চাপ",         "red"),
            ("শ্বাসকষ্ট",                 "red"),
            ("বুক ধড়ফড়",                "yellow"),
            ("হালকা বুকের টান",           "yellow"),
            ("ক্লান্তি",                  "green"),
        ],
        "Telugu": [
            ("ఛాతీ నొప్పి లేదా ఒత్తిడి",  "red"),
            ("శ్వాస ఆడకపోవడం",            "red"),
            ("గుండె దడ",                  "yellow"),
            ("తేలికపాటి ఛాతీ బిగుతు",     "yellow"),
            ("అలసట",                     "green"),
        ],
        "Marathi": [
            ("छातीत दुखणे किंवा दाब",      "red"),
            ("श्वास घेण्यास त्रास",        "red"),
            ("हृदयाची धडधड",              "yellow"),
            ("छातीत सौम्य जडपणा",         "yellow"),
            ("थकवा",                     "green"),
        ],
        "Gujarati": [
            ("છાતીમાં દુખાવો અથવા દબાણ",   "red"),
            ("શ્વાસ લેવામાં તકલીફ",        "red"),
            ("હૃદયના ધબકારા વધવા",         "yellow"),
            ("છાતીમાં હળવી જકડન",          "yellow"),
            ("થાક",                       "green"),
        ],
    },

    "Pelvis & Reproductive": {
        "English": [
            ("Unusual bleeding",          "red"),
            ("Severe pelvic pain",        "red"),
            ("Irregular periods",         "yellow"),
            ("Unusual discharge",         "yellow"),
            ("Pain during intercourse",   "yellow"),
            ("Missed period",             "yellow"),
        ],
        "Hindi": [
            ("असामान्य रक्तस्राव",         "red"),
            ("पेल्विस में तेज़ दर्द",       "red"),
            ("अनियमित माहवारी",            "yellow"),
            ("असामान्य स्राव",             "yellow"),
            ("संभोग के दौरान दर्द",         "yellow"),
            ("माहवारी न आना",              "yellow"),
        ],
        "Tamil": [
            ("அசாதாரண இரத்தப்போக்கு",      "red"),
            ("கடுமையான இடுப்பு வலி",       "red"),
            ("ஒழுங்கற்ற மாதவிடாய்",        "yellow"),
            ("அசாதாரண வெளியேற்றம்",        "yellow"),
            ("உடலுறவின்போது வலி",          "yellow"),
            ("மாதவிடாய் தவறுதல்",          "yellow"),
        ],
        "Bengali": [
            ("অস্বাভাবিক রক্তপাত",          "red"),
            ("তীব্র শ্রোণী ব্যথা",           "red"),
            ("অনিয়মিত মাসিক",              "yellow"),
            ("অস্বাভাবিক স্রাব",             "yellow"),
            ("সহবাসে ব্যথা",               "yellow"),
            ("মাসিক না হওয়া",              "yellow"),
        ],
        "Telugu": [
            ("అసాధారణ రక్తస్రావం",          "red"),
            ("తీవ్రమైన శ్రోణి నొప్పి",       "red"),
            ("అనియమిత రుతుక్రమం",           "yellow"),
            ("అసాధారణ స్రావం",              "yellow"),
            ("సంభోగంలో నొప్పి",             "yellow"),
            ("రుతుక్రమం రాకపోవడం",          "yellow"),
        ],
        "Marathi": [
            ("असामान्य रक्तस्राव",           "red"),
            ("ओटीपोटात तीव्र वेदना",         "red"),
            ("अनियमित मासिक पाळी",          "yellow"),
            ("असामान्य स्राव",              "yellow"),
            ("संभोगादरम्यान वेदना",          "yellow"),
            ("मासिक पाळी न येणे",           "yellow"),
        ],
        "Gujarati": [
            ("અસામાન્ય રક્તસ્રાવ",           "red"),
            ("તીવ્ર પેલ્વિક દુખાવો",          "red"),
            ("અનિયમિત માસિક",               "yellow"),
            ("અસામાન્ય સ્રાવ",              "yellow"),
            ("સંભોગ દરમિયાન દુખાવો",         "yellow"),
            ("માસિક ન આવવું",               "yellow"),
        ],
    },

    "Abdomen & Stomach": {
        "English": [
            ("Severe abdominal pain",   "red"),
            ("Persistent vomiting",     "yellow"),
            ("Bloating / gas",          "green"),
            ("Loss of appetite",        "yellow"),
            ("Nausea",                  "green"),
        ],
        "Hindi": [
            ("पेट में तेज़ दर्द",          "red"),
            ("बार-बार उल्टी",             "yellow"),
            ("पेट फूलना / गैस",           "green"),
            ("भूख न लगना",               "yellow"),
            ("जी मिचलाना",               "green"),
        ],
        "Tamil": [
            ("கடுமையான வயிற்று வலி",      "red"),
            ("தொடர் வாந்தி",              "yellow"),
            ("வயிறு உப்புசம் / வாயு",     "green"),
            ("பசியின்மை",                "yellow"),
            ("குமட்டல்",                  "green"),
        ],
        "Bengali": [
            ("তীব্র পেটব্যথা",             "red"),
            ("বারবার বমি",                "yellow"),
            ("পেট ফাঁপা / গ্যাস",          "green"),
            ("খাবারে অরুচি",              "yellow"),
            ("বমি বমি ভাব",               "green"),
        ],
        "Telugu": [
            ("తీవ్రమైన కడుపు నొప్పి",      "red"),
            ("పదే పదే వాంతులు",            "yellow"),
            ("ఉబ్బరం / గ్యాస్",            "green"),
            ("ఆకలి లేకపోవడం",             "yellow"),
            ("వికారం",                    "green"),
        ],
        "Marathi": [
            ("तीव्र पोटदुखी",              "red"),
            ("वारंवार उलट्या",             "yellow"),
            ("पोट फुगणे / गॅस",           "green"),
            ("भूक न लागणे",               "yellow"),
            ("मळमळ",                     "green"),
        ],
        "Gujarati": [
            ("તીવ્ર પેટ દુખાવો",            "red"),
            ("વારંવાર ઉલ્ટી",              "yellow"),
            ("પેટ ફૂલવું / ગેસ",           "green"),
            ("ભૂખ ન લાગવી",               "yellow"),
            ("ઉબકા",                      "green"),
        ],
    },

    "Legs & Body": {
        "English": [
            ("Swollen legs / ankles",   "red"),
            ("Severe joint pain",       "yellow"),
            ("Mild body ache",          "green"),
            ("Numbness / tingling",     "yellow"),
            ("Weakness",               "green"),
        ],
        "Hindi": [
            ("पैर / टखने सूजना",          "red"),
            ("जोड़ों में तेज़ दर्द",        "yellow"),
            ("हल्का बदन दर्द",            "green"),
            ("सुन्न होना / झुनझुनी",       "yellow"),
            ("कमज़ोरी",                   "green"),
        ],
        "Tamil": [
            ("கால்கள் / கணுக்கால் வீக்கம்", "red"),
            ("கடுமையான மூட்டு வலி",        "yellow"),
            ("லேசான உடல் வலி",            "green"),
            ("மரத்துப்போதல் / கூச்சம்",    "yellow"),
            ("பலவீனம்",                   "green"),
        ],
        "Bengali": [
            ("পা / গোড়ালি ফোলা",           "red"),
            ("তীব্র জয়েন্ট ব্যথা",          "yellow"),
            ("হালকা শরীর ব্যথা",            "green"),
            ("অসাড়তা / ঝিনঝিন",            "yellow"),
            ("দুর্বলতা",                   "green"),
        ],
        "Telugu": [
            ("కాళ్ళు / చీలమండలు వాపు",     "red"),
            ("తీవ్రమైన కీళ్ళ నొప్పి",       "yellow"),
            ("తేలికపాటి శరీర నొప్పి",       "green"),
            ("తిమ్మిరి / జలదరింపు",         "yellow"),
            ("బలహీనత",                    "green"),
        ],
        "Marathi": [
            ("पाय / घोटे सुजणे",            "red"),
            ("सांधेदुखी",                  "yellow"),
            ("सौम्य अंगदुखी",              "green"),
            ("बधिरपणा / मुंग्या",           "yellow"),
            ("अशक्तपणा",                  "green"),
        ],
        "Gujarati": [
            ("પગ / ઘૂંટી સૂજવી",            "red"),
            ("તીવ્ર સાંધાનો દુખાવો",         "yellow"),
            ("હળવો શરીર દુખાવો",            "green"),
            ("સુન્નપણું / ઝણઝણાટ",          "yellow"),
            ("નબળાઈ",                      "green"),
        ],
    },

    "Skin & General": {
        "English": [
            ("High fever (above 102°F)", "red"),
            ("Unexplained weight loss",  "yellow"),
            ("Skin rash or itching",     "yellow"),
            ("Pale / yellowing skin",    "red"),
            ("Mild fatigue",             "green"),
        ],
        "Hindi": [
            ("तेज़ बुखार (102°F से ऊपर)", "red"),
            ("बिना कारण वज़न कम होना",    "yellow"),
            ("त्वचा पर दाने या खुजली",    "yellow"),
            ("पीली या सफ़ेद त्वचा",        "red"),
            ("हल्की थकान",               "green"),
        ],
        "Tamil": [
            ("அதிக காய்ச்சல் (102°F மேல்)", "red"),
            ("காரணமின்றி எடை குறைவு",     "yellow"),
            ("தோல் தடிப்பு அல்லது அரிப்பு", "yellow"),
            ("வெளிர் / மஞ்சள் தோல்",      "red"),
            ("லேசான சோர்வு",              "green"),
        ],
        "Bengali": [
            ("তীব্র জ্বর (102°F এর উপরে)", "red"),
            ("কারণ ছাড়া ওজন কমা",         "yellow"),
            ("ত্বকে ফুসকুড়ি বা চুলকানি",   "yellow"),
            ("ফ্যাকাশে / হলুদ ত্বক",        "red"),
            ("হালকা ক্লান্তি",             "green"),
        ],
        "Telugu": [
            ("అధిక జ్వరం (102°F పైన)",     "red"),
            ("కారణం లేకుండా బరువు తగ్గడం", "yellow"),
            ("చర్మంపై దద్దుర్లు లేదా దురద", "yellow"),
            ("పీలా / పసుపు చర్మం",          "red"),
            ("తేలికపాటి అలసట",            "green"),
        ],
        "Marathi": [
            ("तीव्र ताप (102°F वर)",        "red"),
            ("कारण नसताना वजन कमी होणे",   "yellow"),
            ("त्वचेवर पुरळ किंवा खाज",      "yellow"),
            ("फिकट / पिवळी त्वचा",         "red"),
            ("सौम्य थकवा",                 "green"),
        ],
        "Gujarati": [
            ("તીવ્ર તાવ (102°F થી વધુ)",    "red"),
            ("કારણ વિના વજન ઘટવું",         "yellow"),
            ("ત્વચા પર ફોલ્લા અથવા ખંજવાળ", "yellow"),
            ("નિસ્તેજ / પીળી ત્વચા",        "red"),
            ("હળવો થાક",                   "green"),
        ],
    },
}

# ── Body area labels in native languages ──────────────────

BODY_AREA_LABELS = {
    "English": {
        "Head & Brain":          "Head & Brain",
        "Chest & Heart":         "Chest & Heart",
        "Abdomen & Stomach":     "Abdomen & Stomach",
        "Pelvis & Reproductive": "Pelvis & Reproductive",
        "Legs & Body":           "Legs & Body",
        "Skin & General":        "Skin & General",
    },
    "Hindi": {
        "Head & Brain":          "सिर और दिमाग",
        "Chest & Heart":         "सीना और दिल",
        "Abdomen & Stomach":     "पेट",
        "Pelvis & Reproductive": "पेल्विस और प्रजनन",
        "Legs & Body":           "पैर और शरीर",
        "Skin & General":        "त्वचा और सामान्य",
    },
    "Tamil": {
        "Head & Brain":          "தலை மற்றும் மூளை",
        "Chest & Heart":         "மார்பு மற்றும் இதயம்",
        "Abdomen & Stomach":     "வயிறு",
        "Pelvis & Reproductive": "இடுப்பு மற்றும் இனப்பெருக்கம்",
        "Legs & Body":           "கால்கள் மற்றும் உடல்",
        "Skin & General":        "தோல் மற்றும் பொது",
    },
    "Bengali": {
        "Head & Brain":          "মাথা ও মস্তিষ্ক",
        "Chest & Heart":         "বুক ও হৃদয়",
        "Abdomen & Stomach":     "পেট",
        "Pelvis & Reproductive": "শ্রোণী ও প্রজনন",
        "Legs & Body":           "পা ও শরীর",
        "Skin & General":        "ত্বক ও সাধারণ",
    },
    "Telugu": {
        "Head & Brain":          "తల మరియు మెదడు",
        "Chest & Heart":         "ఛాతీ మరియు హృదయం",
        "Abdomen & Stomach":     "కడుపు",
        "Pelvis & Reproductive": "శ్రోణి మరియు పునరుత్పత్తి",
        "Legs & Body":           "కాళ్ళు మరియు శరీరం",
        "Skin & General":        "చర్మం మరియు సాధారణ",
    },
    "Marathi": {
        "Head & Brain":          "डोके आणि मेंदू",
        "Chest & Heart":         "छाती आणि हृदय",
        "Abdomen & Stomach":     "पोट",
        "Pelvis & Reproductive": "ओटीपोट आणि प्रजनन",
        "Legs & Body":           "पाय आणि शरीर",
        "Skin & General":        "त्वचा आणि सामान्य",
    },
    "Gujarati": {
        "Head & Brain":          "માથું અને મગજ",
        "Chest & Heart":         "છાતી અને હૃદય",
        "Abdomen & Stomach":     "પેટ",
        "Pelvis & Reproductive": "પેલ્વિસ અને પ્રજનન",
        "Legs & Body":           "પગ અને શરીર",
        "Skin & General":        "ત્વચા અને સામાન્ય",
    },
}

# ── Helper: get symptoms for area in chosen language ──────

def get_symptoms_for_area(area, lang):
    lang_symptoms = SYMPTOMS_TRANSLATED.get(area, {})
    return lang_symptoms.get(lang, lang_symptoms.get("English", []))

def get_area_label(area, lang):
    labels = BODY_AREA_LABELS.get(lang, BODY_AREA_LABELS["English"])
    return labels.get(area, area)

# ── Test ──────────────────────────────────────────────────
print("🧪 Testing body diagram in all languages...\n")
test_area = "Pelvis & Reproductive"
for lang in ["English", "Hindi", "Tamil", "Bengali", "Telugu", "Marathi", "Gujarati"]:
    label    = get_area_label(test_area, lang)
    symptoms = get_symptoms_for_area(test_area, lang)
    print(f"  {lang}: {label}")
    for s, level in symptoms[:2]:
        dot = "🔴" if level == "red" else "🟡"
        print(f"    {dot} {s}")
    print()

print("✅ Body diagram multilingual selector ready!")

# ── Red flags in native languages ────────────────────────

RED_FLAGS_TRANSLATED = {
    "unusual bleeding": {
        "English": "Could indicate cervical or uterine issues. Early screening is critical.",
        "Hindi":   "यह गर्भाशय या सर्वाइकल समस्या हो सकती है। तुरंत जाँच करवाएं।",
        "Tamil":   "கர்ப்பப்பை அல்லது கர்ப்பப்பை வாய் பிரச்சனை இருக்கலாம். உடனே பரிசோதனை செய்யுங்கள்।",
        "Bengali": "জরায়ু বা সার্ভিকাল সমস্যা হতে পারে। অবিলম্বে পরীক্ষা করুন।",
        "Telugu":  "గర్భాశయ లేదా సర్వైకల్ సమస్య కావచ్చు. వెంటనే పరీక్ష చేయించుకోండి.",
        "Marathi": "गर्भाशय किंवा सर्व्हायकल समस्या असू शकते. त्वरित तपासणी करा.",
        "Gujarati":"ગર્ભાશય અથવા સર્વાઇકલ સમસ્યા હોઈ શકે. તરત જ તપાસ કરાવો.",
    },
    "severe pelvic pain": {
        "English": "May indicate endometriosis, ovarian cyst, or ectopic pregnancy.",
        "Hindi":   "यह एंडोमेट्रियोसिस, ओवेरियन सिस्ट या एक्टोपिक प्रेगनेंसी हो सकती है।",
        "Tamil":   "எண்டோமெட்ரியோசிஸ், கருப்பை நீர்க்கட்டி அல்லது எக்டோபிக் கர்ப்பம் இருக்கலாம்।",
        "Bengali": "এন্ডোমেট্রিওসিস, ওভারিয়ান সিস্ট বা এক্টোপিক গর্ভাবস্থা হতে পারে।",
        "Telugu":  "ఎండోమెట్రియోసిస్, అండాశయ సిస్ట్ లేదా ఎక్టోపిక్ గర్భం కావచ్చు.",
        "Marathi": "एंडोमेट्रिओसिस, ओव्हेरियन सिस्ट किंवा एक्टोपिक गर्भधारणा असू शकते.",
        "Gujarati":"એન્ડોમેટ્રિઓસિસ, ઓવેરિયન સિસ્ટ અથવા એક્ટોપિક ગર્ભાવસ્થા હોઈ શકે.",
    },
    "chest pain or pressure": {
        "English": "Women's heart attack symptoms are often dismissed. Do not ignore.",
        "Hindi":   "महिलाओं में दिल के दौरे के लक्षण अक्सर नज़रअंदाज़ होते हैं। ध्यान दें।",
        "Tamil":   "பெண்களின் மாரடைப்பு அறிகுறிகள் அடிக்கடி புறக்கணிக்கப்படுகின்றன। கவனிக்கவும்।",
        "Bengali": "মহিলাদের হার্ট অ্যাটাকের লক্ষণ প্রায়ই উপেক্ষিত হয়। মনোযোগ দিন।",
        "Telugu":  "మహిళల గుండెపోటు లక్షణాలు తరచుగా నిర్లక్ష్యం చేయబడతాయి. శ్రద్ధ వహించండి.",
        "Marathi": "महिलांच्या हृदयविकाराची लक्षणे अनेकदा दुर्लक्षित होतात. लक्ष द्या.",
        "Gujarati":"સ્ત્રીઓના હૃદયરોગના લક્ષણો ઘણીવાર અવગણવામાં આવે છે. ધ્યાન આપો.",
    },
    "severe headache": {
        "English": "Could indicate high blood pressure or neurological issue.",
        "Hindi":   "यह हाई ब्लड प्रेशर या न्यूरोलॉजिकल समस्या हो सकती है।",
        "Tamil":   "உயர் இரத்த அழுத்தம் அல்லது நரம்பியல் பிரச்சனை இருக்கலாம்।",
        "Bengali": "উচ্চ রক্তচাপ বা স্নায়বিক সমস্যা হতে পারে।",
        "Telugu":  "అధిక రక్తపోటు లేదా నాడీ సమస్య కావచ్చు.",
        "Marathi": "उच्च रक्तदाब किंवा न्यूरोलॉजिकल समस्या असू शकते.",
        "Gujarati":"ઉચ્ચ રક્તદાબ અથવા ન્યુરોલોજિકલ સમસ્યા હોઈ શકે.",
    },
    "swollen legs or ankles": {
        "English": "Possible sign of preeclampsia if pregnant, or heart/kidney issue.",
        "Hindi":   "गर्भावस्था में प्रीएक्लेम्पसिया या दिल/किडनी की समस्या हो सकती है।",
        "Tamil":   "கர்ப்பமாக இருந்தால் ப்ரீக்லாம்ப்சியா அல்லது இதய/சிறுநீரக பிரச்சனை இருக்கலாம்।",
        "Bengali": "গর্ভাবস্থায় প্রিক্ল্যাম্পসিয়া বা হার্ট/কিডনি সমস্যার লক্ষণ হতে পারে।",
        "Telugu":  "గర్భంలో ప్రీఎక్లాంప్సియా లేదా గుండె/మూత్రపిండాల సమస్య కావచ్చు.",
        "Marathi": "गर्भधारणेत प्रीएक्लेम्पसिया किंवा हृदय/मूत्रपिंड समस्या असू शकते.",
        "Gujarati":"ગર્ભાવસ્થામાં પ્રીએક્લેમ્પ્સિયા અથવા હૃદય/કિડની સમસ્યા હોઈ શકે.",
    },
    "pale or yellowing skin": {
        "English": "May indicate severe anemia — very common and dangerous in women.",
        "Hindi":   "गंभीर एनीमिया हो सकता है — महिलाओं में बहुत आम और खतरनाक।",
        "Tamil":   "கடுமையான இரத்த சோகை இருக்கலாம் — பெண்களில் மிகவும் பொதுவானது.",
        "Bengali": "গুরুতর রক্তাল্পতা হতে পারে — মহিলাদের মধ্যে খুবই সাধারণ ও বিপজ্জনক।",
        "Telugu":  "తీవ్రమైన రక్తహీనత కావచ్చు — మహిళల్లో చాలా సాధారణం మరియు ప్రమాదకరం.",
        "Marathi": "तीव्र अशक्तपणा असू शकतो — महिलांमध्ये अतिशय सामान्य आणि धोकादायक.",
        "Gujarati":"ગંભીર એનિમિયા હોઈ શકે — સ્ત્રીઓમાં ખૂબ સામાન્ય અને ખતરનાક.",
    },
    "high fever": {
        "English": "Needs immediate attention — could be infection or severe illness.",
        "Hindi":   "तुरंत ध्यान दें — संक्रमण या गंभीर बीमारी हो सकती है।",
        "Tamil":   "உடனடி கவனம் தேவை — தொற்று அல்லது கடுமையான நோய் இருக்கலாம்।",
        "Bengali": "তাৎক্ষণিক মনোযোগ দরকার — সংক্রমণ বা গুরুতর অসুস্থতা হতে পারে।",
        "Telugu":  "వెంటనే శ్రద్ధ తీసుకోండి — సంక్రమణ లేదా తీవ్రమైన అనారోగ్యం కావచ్చు.",
        "Marathi": "त्वरित लक्ष द्या — संसर्ग किंवा गंभीर आजार असू शकतो.",
        "Gujarati":"તાત્કાલિક ધ્યાન આપો — ચેપ અથવા ગંભીર બીમારી હોઈ શકે.",
    },
}

# ── Maternal warnings in native languages ─────────────────

MATERNAL_WARNINGS_TRANSLATED = {
    "unusual bleeding": {
        "English": "🤰 Bleeding during pregnancy is always serious. Go to hospital NOW.",
        "Hindi":   "🤰 गर्भावस्था में रक्तस्राव हमेशा गंभीर है। अभी अस्पताल जाएं।",
        "Tamil":   "🤰 கர்ப்ப காலத்தில் இரத்தப்போக்கு எப்போதும் தீவிரமானது. இப்போதே மருத்துவமனை செல்லுங்கள்।",
        "Bengali": "🤰 গর্ভাবস্থায় রক্তপাত সবসময় গুরুতর। এখনই হাসপাতালে যান।",
        "Telugu":  "🤰 గర్భంలో రక్తస్రావం ఎల్లప్పుడూ తీవ్రమైనది. ఇప్పుడే ఆసుపత్రికి వెళ్ళండి.",
        "Marathi": "🤰 गर्भधारणेत रक्तस्राव नेहमीच गंभीर असतो. आत्ताच रुग्णालयात जा.",
        "Gujarati":"🤰 ગર્ભાવસ્થામાં રક્તસ્રાવ હંમેશા ગંભીર છે. અત્યારે જ હોસ્પિટલ જાઓ.",
    },
    "severe pelvic pain": {
        "English": "🤰 Could indicate miscarriage or ectopic pregnancy. Emergency care needed.",
        "Hindi":   "🤰 गर्भपात या एक्टोपिक प्रेगनेंसी हो सकती है। तुरंत आपातकालीन देखभाल लें।",
        "Tamil":   "🤰 கருச்சிதைவு அல்லது எக்டோபிக் கர்ப்பம் இருக்கலாம். அவசர சிகிச்சை தேவை.",
        "Bengali": "🤰 গর্ভপাত বা এক্টোপিক গর্ভাবস্থা হতে পারে। জরুরি যত্ন প্রয়োজন।",
        "Telugu":  "🤰 గర్భస్రావం లేదా ఎక్టోపిక్ గర్భం కావచ్చు. అత్యవసర సంరక్షణ అవసరం.",
        "Marathi": "🤰 गर्भपात किंवा एक्टोपिक गर्भधारणा असू शकते. तातडीची काळजी घ्या.",
        "Gujarati":"🤰 કસુવાવડ અથવા એક્ટોપિક ગર્ભાવસ્થા હોઈ શકે. તાત્કાલિક સારવાર લો.",
    },
    "swollen legs or ankles": {
        "English": "🤰 Sign of preeclampsia — dangerous in pregnancy. See doctor today.",
        "Hindi":   "🤰 प्रीएक्लेम्पसिया का संकेत — गर्भावस्था में खतरनाक। आज ही डॉक्टर को दिखाएं।",
        "Tamil":   "🤰 ப்ரீக்லாம்ப்சியாவின் அறிகுறி — கர்ப்பத்தில் ஆபத்தானது. இன்றே மருத்துவரை பாருங்கள்.",
        "Bengali": "🤰 প্রিক্ল্যাম্পসিয়ার লক্ষণ — গর্ভাবস্থায় বিপজ্জনক। আজই ডাক্তার দেখুন।",
        "Telugu":  "🤰 ప్రీఎక్లాంప్సియా సంకేతం — గర్భంలో ప్రమాదకరం. ఈరోజే వైద్యుడిని చూడండి.",
        "Marathi": "🤰 प्रीएक्लेम्पसियाचे लक्षण — गर्भधारणेत धोकादायक. आजच डॉक्टरांना भेटा.",
        "Gujarati":"🤰 પ્રીએક્લેમ્પ્સિયાની નિશાની — ગર્ભાવસ્થામાં ખતરનાક. આજે જ ડૉક્ટર પાસે જાઓ.",
    },
    "severe headache": {
        "English": "🤰 Headache + pregnancy = possible preeclampsia. Do not wait.",
        "Hindi":   "🤰 सिरदर्द + गर्भावस्था = प्रीएक्लेम्पसिया हो सकता है। इंतज़ार मत करें।",
        "Tamil":   "🤰 தலைவலி + கர்ப்பம் = ப்ரீக்லாம்ப்சியா இருக்கலாம். காத்திருக்காதீர்கள்.",
        "Bengali": "🤰 মাথাব্যথা + গর্ভাবস্থা = প্রিক্ল্যাম্পসিয়া হতে পারে। অপেক্ষা করবেন না।",
        "Telugu":  "🤰 తలనొప్పి + గర్భం = ప్రీఎక్లాంప్సియా కావచ్చు. వేచి ఉండకండి.",
        "Marathi": "🤰 डोकेदुखी + गर्भधारणा = प्रीएक्लेम्पसिया असू शकतो. वाट पाहू नका.",
        "Gujarati":"🤰 માથાનો દુખાવો + ગર્ભાવસ્થા = પ્રીએક્લેમ્પ્સિયા હોઈ શકે. રાહ ન જુઓ.",
    },
    "blurred vision": {
        "English": "🤰 Vision changes in pregnancy need immediate evaluation.",
        "Hindi":   "🤰 गर्भावस्था में दृष्टि परिवर्तन के लिए तुरंत जाँच ज़रूरी है।",
        "Tamil":   "🤰 கர்ப்ப காலத்தில் பார்வை மாற்றங்களுக்கு உடனடி மதிப்பீடு தேவை.",
        "Bengali": "🤰 গর্ভাবস্থায় দৃষ্টি পরিবর্তনের জন্য তাৎক্ষণিক মূল্যায়ন প্রয়োজন।",
        "Telugu":  "🤰 గర్భంలో దృష్టి మార్పులకు వెంటనే మూల్యాంకనం అవసరం.",
        "Marathi": "🤰 गर्भधारणेत दृष्टी बदलांसाठी त्वरित तपासणी आवश्यक आहे.",
        "Gujarati":"🤰 ગર્ભાવસ્થામાં દ્રષ્ટિ ફેરફારો માટે તાત્કાલિક મૂલ્યાંકન જરૂરી છે.",
    },
}

# ── Screening reminders in native languages ───────────────

SCREENINGS_TRANSLATED = {
    "English": [
        ("Cervical Cancer (Pap Smear)",  "Every 3 years after age 21"),
        ("Breast self-exam",             "Every month at home"),
        ("Blood Pressure check",         "Every 6 months"),
        ("Hemoglobin / Anemia",          "Every year"),
        ("Blood Sugar",                  "Every year after age 30"),
    ],
    "Hindi": [
        ("सर्वाइकल कैंसर (पैप स्मीयर)", "21 साल के बाद हर 3 साल में"),
        ("स्तन स्व-जाँच",               "घर पर हर महीने"),
        ("ब्लड प्रेशर जाँच",             "हर 6 महीने में"),
        ("हीमोग्लोबिन / एनीमिया",        "हर साल"),
        ("ब्लड शुगर",                    "30 साल के बाद हर साल"),
    ],
    "Tamil": [
        ("கர்ப்பப்பை வாய் புற்றுநோய் (பாப் ஸ்மியர்)", "21 வயதிற்கு பிறகு 3 ஆண்டுகளுக்கு ஒரு முறை"),
        ("மார்பக சுய பரிசோதனை",         "வீட்டில் ஒவ்வொரு மாதமும்"),
        ("இரத்த அழுத்தம் சோதனை",        "ஒவ்வொரு 6 மாதத்திற்கும்"),
        ("ஹீமோகுளோபின் / இரத்த சோகை",   "ஒவ்வொரு ஆண்டும்"),
        ("இரத்த சர்க்கரை",               "30 வயதிற்கு பிறகு ஒவ்வொரு ஆண்டும்"),
    ],
    "Bengali": [
        ("সার্ভিকাল ক্যান্সার (প্যাপ স্মিয়ার)", "২১ বছরের পরে প্রতি ৩ বছরে"),
        ("স্তন স্ব-পরীক্ষা",             "বাড়িতে প্রতি মাসে"),
        ("রক্তচাপ পরীক্ষা",              "প্রতি ৬ মাসে"),
        ("হিমোগ্লোবিন / রক্তাল্পতা",     "প্রতি বছর"),
        ("রক্তে শর্করা",                 "৩০ বছরের পরে প্রতি বছর"),
    ],
    "Telugu": [
        ("సర్వైకల్ క్యాన్సర్ (పాప్ స్మియర్)", "21 సంవత్సరాల తర్వాత ప్రతి 3 సంవత్సరాలకు"),
        ("స్తన స్వయం పరీక్ష",            "నెలకు ఒకసారి ఇంట్లో"),
        ("రక్తపోటు తనిఖీ",               "ప్రతి 6 నెలలకు"),
        ("హిమోగ్లోబిన్ / రక్తహీనత",      "ప్రతి సంవత్సరం"),
        ("రక్తంలో చక్కెర",               "30 సంవత్సరాల తర్వాత ప్రతి సంవత్సరం"),
    ],
    "Marathi": [
        ("सर्व्हायकल कॅन्सर (पॅप स्मीअर)", "21 वर्षांनंतर दर 3 वर्षांनी"),
        ("स्तन स्व-तपासणी",              "घरी दर महिन्याला"),
        ("रक्तदाब तपासणी",               "दर 6 महिन्यांनी"),
        ("हिमोग्लोबिन / अशक्तपणा",       "दर वर्षी"),
        ("रक्तातील साखर",                "30 वर्षांनंतर दर वर्षी"),
    ],
    "Gujarati": [
        ("સર્વાઇકલ કેન્સર (પેપ સ્મિયર)", "21 વર્ષ પછી દર 3 વર્ષે"),
        ("સ્તન સ્વ-પરીક્ષણ",             "ઘરે દર મહિને"),
        ("બ્લડ પ્રેશર તપાસ",             "દર 6 મહિને"),
        ("હિમોગ્લોબિન / એનિમિયા",        "દર વર્ષે"),
        ("બ્લડ સુગર",                    "30 વર્ષ પછી દર વર્ષે"),
    ],
}

# ── Helper functions ──────────────────────────────────────

def get_red_flag_reason(symptom, lang):
    symptom_clean = symptom.lower().strip()
    flags = RED_FLAGS_TRANSLATED.get(symptom_clean, {})
    return flags.get(lang, flags.get("English", ""))

def get_maternal_warning(symptom, lang):
    symptom_clean = symptom.lower().strip()
    warnings = MATERNAL_WARNINGS_TRANSLATED.get(symptom_clean, {})
    return warnings.get(lang, warnings.get("English", ""))

def get_screenings(lang):
    return SCREENINGS_TRANSLATED.get(lang, SCREENINGS_TRANSLATED["English"])

def detect_red_flags(selected_symptoms, lang):
    red_flags     = []
    for symptom in selected_symptoms:
        reason = get_red_flag_reason(symptom, lang)
        if reason:
            red_flags.append((symptom, reason))
    return red_flags

def detect_maternal_alerts(selected_symptoms, is_pregnant, lang):
    if not is_pregnant:
        return []
    alerts = []
    for symptom in selected_symptoms:
        warning = get_maternal_warning(symptom, lang)
        if warning:
            alerts.append((symptom, warning))
    return alerts

# ── Test ──────────────────────────────────────────────────

print("🧪 Testing red flag detection in all languages...\n")

test_symptoms  = ["unusual bleeding", "severe pelvic pain", "severe headache"]
test_lang      = "Hindi"
test_pregnant  = True

red_flags = detect_red_flags(test_symptoms, test_lang)
maternal  = detect_maternal_alerts(test_symptoms, test_pregnant, test_lang)
screenings = get_screenings(test_lang)

print(f"  🔴 Red Flags ({test_lang}):")
for s, r in red_flags:
    print(f"    ● {s}: {r}\n")

print(f"  🤰 Maternal Alerts ({test_lang}):")
for s, w in maternal:
    print(f"    ● {w}\n")

print(f"  🔬 Screenings ({test_lang}):")
for test, freq in screenings:
    print(f"    ✓ {test} — {freq}")

print("\n✅ Red flag detection + pregnancy alerts ready!")

import gradio as gr

# ── Language button labels ────────────────────────────────
LANG_BUTTONS = {
    "English":  "🇮🇳 English",
    "Hindi":    "🇮🇳 हिंदी",
    "Tamil":    "🇮🇳 தமிழ்",
    "Bengali":  "🇮🇳 বাংলা",
    "Telugu":   "🇮🇳 తెలుగు",
    "Marathi":  "🇮🇳 मराठी",
    "Gujarati": "🇮🇳 ગુજરાતી",
}

# ── UI prompts in native language ─────────────────────────
UI_TEXT = {
    "English": {
        "greeting":    "Hello! I am Sakhi 🌸 How can I help you today?",
        "pregnant_q":  "Are you pregnant?",
        "yes":         "Yes 🤰",
        "no":          "No",
        "how_tell":    "How do you want to tell Sakhi what's wrong?",
        "tap":         "🫀 Tap body",
        "speak":       "🎤 Speak",
        "write":       "✍️ Write",
        "select_area": "Where does it hurt? Tap the area:",
        "select_symp": "What are you feeling? (select all that apply)",
        "or_speak":    "Or speak / write your symptoms:",
        "speak_ph":    "Record your voice...",
        "write_ph":    "Describe how you feel... e.g. stomach pain, no periods",
        "analyze":     "🔍 Ask Sakhi",
        "result":      "Sakhi says:",
    },
    "Hindi": {
        "greeting":    "नमस्ते! मैं Sakhi हूँ 🌸 आज मैं आपकी कैसे मदद करूँ?",
        "pregnant_q":  "क्या आप गर्भवती हैं?",
        "yes":         "हाँ 🤰",
        "no":          "नहीं",
        "how_tell":    "Sakhi को कैसे बताना चाहती हैं?",
        "tap":         "🫀 शरीर पर टैप करें",
        "speak":       "🎤 बोलें",
        "write":       "✍️ लिखें",
        "select_area": "कहाँ दर्द है? उस जगह को चुनें:",
        "select_symp": "क्या महसूस हो रहा है? (सब चुनें जो सही हो)",
        "or_speak":    "या बोलें / लिखें:",
        "speak_ph":    "आवाज़ रिकॉर्ड करें...",
        "write_ph":    "बताएं कैसा महसूस हो रहा है... जैसे पेट दर्द, माहवारी नहीं आई",
        "analyze":     "🔍 Sakhi से पूछें",
        "result":      "Sakhi कहती है:",
    },
    "Tamil": {
        "greeting":    "வணக்கம்! நான் Sakhi 🌸 இன்று உங்களுக்கு எப்படி உதவட்டும்?",
        "pregnant_q":  "நீங்கள் கர்ப்பமாக இருக்கிறீர்களா?",
        "yes":         "ஆம் 🤰",
        "no":          "இல்லை",
        "how_tell":    "Sakhi-கிடம் எப்படி சொல்ல விரும்புகிறீர்கள்?",
        "tap":         "🫀 உடலில் தொடுங்கள்",
        "speak":       "🎤 பேசுங்கள்",
        "write":       "✍️ எழுதுங்கள்",
        "select_area": "எங்கே வலிக்கிறது? அந்த இடத்தை தேர்வு செய்யுங்கள்:",
        "select_symp": "என்ன உணர்கிறீர்கள்? (பொருந்தும் அனைத்தையும் தேர்ந்தெடுக்கவும்)",
        "or_speak":    "அல்லது பேசுங்கள் / எழுதுங்கள்:",
        "speak_ph":    "குரலை பதிவு செய்யுங்கள்...",
        "write_ph":    "எப்படி உணர்கிறீர்கள் என்று சொல்லுங்கள்...",
        "analyze":     "🔍 Sakhi-யிடம் கேளுங்கள்",
        "result":      "Sakhi சொல்கிறார்:",
    },
    "Bengali": {
        "greeting":    "নমস্কার! আমি Sakhi 🌸 আজ আপনাকে কীভাবে সাহায্য করতে পারি?",
        "pregnant_q":  "আপনি কি গর্ভবতী?",
        "yes":         "হ্যাঁ 🤰",
        "no":          "না",
        "how_tell":    "Sakhi-কে কীভাবে বলতে চান?",
        "tap":         "🫀 শরীরে ট্যাপ করুন",
        "speak":       "🎤 বলুন",
        "write":       "✍️ লিখুন",
        "select_area": "কোথায় ব্যথা? সেই জায়গা বেছে নিন:",
        "select_symp": "কী অনুভব করছেন? (সব প্রযোজ্যগুলো বেছে নিন)",
        "or_speak":    "অথবা বলুন / লিখুন:",
        "speak_ph":    "আপনার কণ্ঠ রেকর্ড করুন...",
        "write_ph":    "কেমন লাগছে বলুন... যেমন পেটব্যথা, মাসিক হয়নি",
        "analyze":     "🔍 Sakhi-কে জিজ্ঞেস করুন",
        "result":      "Sakhi বলছেন:",
    },
    "Telugu": {
        "greeting":    "నమస్కారం! నేను Sakhi 🌸 ఈరోజు మీకు ఎలా సహాయం చేయాలి?",
        "pregnant_q":  "మీరు గర్భవతిగా ఉన్నారా?",
        "yes":         "అవును 🤰",
        "no":          "లేదు",
        "how_tell":    "Sakhi-కి ఎలా చెప్పాలనుకుంటున్నారు?",
        "tap":         "🫀 శరీరంపై నొక్కండి",
        "speak":       "🎤 మాట్లాడండి",
        "write":       "✍️ రాయండి",
        "select_area": "ఎక్కడ నొప్పిగా ఉంది? ఆ భాగాన్ని ఎంచుకోండి:",
        "select_symp": "ఏమి అనుభవిస్తున్నారు? (వర్తించే అన్నీ ఎంచుకోండి)",
        "or_speak":    "లేదా మాట్లాడండి / రాయండి:",
        "speak_ph":    "మీ గొంతు రికార్డ్ చేయండి...",
        "write_ph":    "ఎలా అనిపిస్తుందో చెప్పండి... ఉదా: కడుపు నొప్పి, నెలసరి రాలేదు",
        "analyze":     "🔍 Sakhi-ని అడగండి",
        "result":      "Sakhi చెప్తోంది:",
    },
    "Marathi": {
        "greeting":    "नमस्ते! मी Sakhi आहे 🌸 आज मी तुम्हाला कशी मदत करू?",
        "pregnant_q":  "तुम्ही गर्भवती आहात का?",
        "yes":         "हो 🤰",
        "no":          "नाही",
        "how_tell":    "Sakhi ला कसे सांगायचे आहे?",
        "tap":         "🫀 शरीरावर टॅप करा",
        "speak":       "🎤 बोला",
        "write":       "✍️ लिहा",
        "select_area": "कुठे दुखतंय? ती जागा निवडा:",
        "select_symp": "काय जाणवतंय? (सर्व लागू पर्याय निवडा)",
        "or_speak":    "किंवा बोला / लिहा:",
        "speak_ph":    "आवाज रेकॉर्ड करा...",
        "write_ph":    "कसं वाटतंय ते सांगा... उदा: पोटदुखी, मासिक आलं नाही",
        "analyze":     "🔍 Sakhi ला विचारा",
        "result":      "Sakhi म्हणते:",
    },
    "Gujarati": {
        "greeting":    "નમસ્તે! હું Sakhi છું 🌸 આજે હું તમને કેવી રીતે મદદ કરી શકું?",
        "pregnant_q":  "શું તમે ગર્ભવતી છો?",
        "yes":         "હા 🤰",
        "no":          "ના",
        "how_tell":    "Sakhi ને કેવી રીતે કહેવું છે?",
        "tap":         "🫀 શરીર પર ટૅપ કરો",
        "speak":       "🎤 બોલો",
        "write":       "✍️ લખો",
        "select_area": "ક્યાં દુખે છે? તે જગ્યા પસંદ કરો:",
        "select_symp": "શું અનુભવ થાય છે? (બધા લાગુ પડતા પસંદ કરો)",
        "or_speak":    "અથવા બોલો / લખો:",
        "speak_ph":    "તમારો અવાજ રેકોર્ડ કરો...",
        "write_ph":    "કેવું લાગે છે તે જણાવો... દા.ત. પેટ દુખાવો, માસિક ન આવ્યું",
        "analyze":     "🔍 Sakhi ને પૂછો",
        "result":      "Sakhi કહે છે:",
    },
}

# ── Core analysis function ────────────────────────────────

def analyze(lang, pregnant, area, symptoms_selected,
            voice_input, text_input):

    is_pregnant = pregnant == UI_TEXT[lang]["yes"]
    ui          = UI_TEXT[lang]

    # Collect symptoms from all 3 inputs
    all_symptoms = list(symptoms_selected) if symptoms_selected else []

    # Text input → NLP extraction
    if text_input and text_input.strip():
        try:
            bart_result = symptom_extractor(
                text_input,
                candidate_labels=ALL_SYMPTOMS,
                multi_label=True,
            )
            nlp_symptoms = [
                label for label, score
                in zip(bart_result["labels"], bart_result["scores"])
                if score > 0.15
            ][:5]
            all_symptoms += nlp_symptoms
        except:
            pass

    # Voice input → transcribe → NLP
    if voice_input:
        try:
            import whisper
            model  = whisper.load_model("tiny")
            result = model.transcribe(voice_input)
            spoken = result["text"]
            bart_result = symptom_extractor(
                spoken,
                candidate_labels=ALL_SYMPTOMS,
                multi_label=True,
            )
            voice_symptoms = [
                label for label, score
                in zip(bart_result["labels"], bart_result["scores"])
                if score > 0.15
            ][:5]
            all_symptoms += voice_symptoms
        except:
            pass

    # Deduplicate
    all_symptoms = list(dict.fromkeys(all_symptoms))

    if not all_symptoms:
        return f"""
        <div style='background:#1a0033; border-radius:16px; padding:20px;
                    font-family:Arial; text-align:center;'>
            <p style='color:#dda0dd; font-size:1.1em;'>
                {ui['greeting']}<br><br>
                ⚠️ Please tap, speak or write your symptoms first.
            </p>
        </div>
        """

    # Run full pipeline
    try:
        report = run_sakhai_pipeline(
            user_input   = text_input or " ".join(all_symptoms),
            language     = lang,
            is_pregnant  = is_pregnant,
        )
        report["extracted"] = all_symptoms
    except Exception as e:
        return f"<p style='color:red;'>Error: {str(e)}</p>"

    # ── Detect red flags ──────────────────────────────────
    red_flags     = detect_red_flags(all_symptoms, lang)
    maternal      = detect_maternal_alerts(all_symptoms, is_pregnant, lang)
    screenings    = get_screenings(lang)
    strings, recs = get_translated_report_text(
        report["urgency"], [], report["flan_recs"], lang
    )

    urgency       = report["urgency"]
    verdict_color = "#ff4444" if urgency == "HIGH" else ("#ffd93d" if urgency == "MODERATE" else "#6bcb77")
    verdict_bg    = "#2d0000" if urgency == "HIGH" else ("#2d2000" if urgency == "MODERATE" else "#002d00")
    urgency_emoji = "🔴" if urgency == "HIGH" else ("🟡" if urgency == "MODERATE" else "🟢")

    # ── Symptom tags ──────────────────────────────────────
    symptom_tags = "".join(f"""
        <span style='background:#3d0066; color:#e0b0ff;
                     padding:5px 12px; border-radius:20px;
                     margin:3px; display:inline-block;'>
            {s}
        </span>""" for s in all_symptoms)

    # Pre-construct conditional HTML blocks
    red_flags_block = ""
    if red_flags:
        red_flags_block = f"""
        <div style='background:#1a0000; border-radius:12px;
                    padding:15px; margin:12px 0;'>
            {red_flag_html}
        </div>"""

    maternal_alerts_block = ""
    if maternal:
        maternal_alerts_block = f"""
        <div style='background:#1a0d00; border-radius:12px;
                    padding:15px; margin:12px 0;'>
            {maternal_html}
        </div>"""

    possible_conditions_block = ""
    if report['diseases']:
        pcos_risk_html = f"<p style='color:#aaaaff;'>💊 PCOS Risk: <b>{report['pcos_risk']}%</b></p>" \
                           if report['pcos_risk'] > 20 else ""
        possible_conditions_block = f"""
        <div style='background:#1f0044; border-radius:12px;
                    padding:15px; margin:12px 0;'>
            <h3 style='color:#dda0dd; margin-top:0; font-size:1em;'>
                🔍 Possible Conditions
            </h3>
            {disease_html}
            {pcos_risk_html}
        </div>"""


    html = f"""
    <div style='background:#1a0033; border-radius:16px; padding:25px;
                font-family:Arial,sans-serif;'>

        <!-- Greeting -->
        <div style='text-align:center; margin-bottom:20px;'>
            <h2 style='color:#ff69b4; font-size:2.5em; margin:0;'>🌸 SakhiAI</h2>
            <p style='color:#dda0dd; margin:5px 0; font-style:italic;'>
                {ui['result']}
            </p>
        </div>

        <!-- Symptoms detected -->
        <div style='background:#2a0044; border-radius:12px;
                    padding:15px; margin:12px 0;'>
            <p style='color:#9370db; margin:0 0 10px 0; font-size:0.9em;'>
                🧠 AI detected these symptoms:
            </p>
            {symptom_tags}
        </div>

        <!-- Verdict — BIG and clear -->
        <div style='background:{verdict_bg}; border-radius:12px;
                    padding:20px; margin:12px 0; text-align:center;'>
            <h2 style='color:{verdict_color}; margin:0; font-size:1.8em;'>
                {urgency_emoji} {strings[urgency.lower()] if urgency.lower() in strings else strings["urgent"]}
            </h2>
        </div>

        <!-- Red flags -->
        {red_flags_block}

        <!-- Maternal alerts -->
        {maternal_alerts_block}

        <!-- Possible conditions -->
        {possible_conditions_block}

        <!-- AI Recommendations -->
        <div style='background:#1f0044; border-radius:12px;
                    padding:15px; margin:12px 0;'>
            <h3 style='color:#dda0dd; margin-top:0; font-size:1em;'>
                💡 {strings['recs_title']}
            </h3>
            <p style='color:#c8a0e8; line-height:1.8;'>{recs}</p>
        </div>

        <!-- Screenings -->
        <div style='background:#1f0044; border-radius:12px;
                    padding:15px; margin:12px 0;'>
            <h3 style='color:#dda0dd; margin-top:0; font-size:1em;'>
                🔬 {strings['screening']}
            </h3>
            {screening_html}
        </div>

        <!-- See doctor -->
        <div style='background:#2a0044; border-radius:12px;
                    padding:15px; margin:12px 0; text-align:center;'>
            <p style='color:#ff69b4; font-size:1.1em; margin:0;'>
                👩‍⚕️ {strings['see_doctor']}
            </p>
        </div>

        <!-- Footer -->
        <p style='color:#9370db; text-align:center;
                  font-size:0.8em; margin-top:15px;'>
            SakhiAI — Because every woman deserves to be heard. 🌸<br>
            WiCSCon HackHerThon '26 | Ashoka University
        </p>
    </div>
    """
    return html


# ── Build Gradio App ──────────────────────────────────────

with gr.Blocks(
    theme=gr.themes.Base(),
    css="""
        body, .gradio-container {
            background: #0d0020 !important;
            font-family: Arial, sans-serif;
        }
        .gr-button {
            font-size: 1.1em !important;
            padding: 12px !important;
        }
        label { color: #dda0dd !important; }
    """
) as demo:

    # ── State ─────────────────────────────────────────────
    state_lang = gr.State("Hindi")

    # ── Header ────────────────────────────────────────────
    gr.HTML("""
    <div style='background:linear-gradient(135deg,#1a0033,#3d0066);
                border-radius:16px; padding:25px; text-align:center;
                margin-bottom:10px;'>
        <h1 style='color:#ff69b4; font-size:2.5em; margin:0;'>🌸 SakhiAI</h1>
        <p style='color:#dda0dd; margin:5px 0;'>Her First Doctor</p>
        <p style='color:#c8a0e8; font-size:0.85em; font-style:italic;'>
            Every woman deserves a friend who knows health.
        </p>
    </div>
    """)

    # ── Step 1: Language ──────────────────────────────────
    gr.HTML("<h3 style='color:#dda0dd; text-align:center;'>🌐 Choose your language / अपनी भाषा चुनें</h3>")

    with gr.Row():
        lang = gr.Dropdown(
            choices=list(LANG_BUTTONS.keys()),
            value="Hindi",
            label="",
            scale=2,
        )

    # ── Step 2: Pregnant ──────────────────────────────────
    gr.HTML("<h3 style='color:#dda0dd; text-align:center;'>🤰 Are you pregnant? / क्या आप गर्भवती हैं?</h3>")

    pregnant = gr.Radio(
        choices=["हाँ 🤰", "नहीं"],
        value="नहीं",
        label="",
    )

    # ── Step 3: Body area ─────────────────────────────────
    gr.HTML("<h3 style='color:#dda0dd; text-align:center;'>🫀 Where does it hurt? / कहाँ दर्द है?</h3>")

    gr.HTML("""
    <div style='background:#1a0033; border-radius:12px; padding:15px;
                font-family:monospace; text-align:center;'>
        <pre style='color:#c8a0e8; font-size:1em; line-height:1.8;'>
    ╭───╮
    │ O │  ← 1. सिर / Head
    ╰───╯
      │
   ╭──┴──╮
   │  ♥  │  ← 2. सीना / Chest
   ╰──┬──╯
      │
   ╭──┴──╮
   │     │  ← 3. पेट / Abdomen
   ╰──┬──╯
      │
   ╭──┴──╮
   │  ♀  │  ← 4. पेल्विस / Pelvis
   ╰──┬──╯
     ╱ ╲
    ╱   ╲   ← 5. पैर / Legs
        </pre>
        <p style='color:#9370db;'>6. त्वचा / Skin & General</p>
    </div>
    """)

    area = gr.Radio(
        choices=[
            "Head & Brain",
            "Chest & Heart",
            "Abdomen & Stomach",
            "Pelvis & Reproductive",
            "Legs & Body",
            "Skin & General",
        ],
        value="Pelvis & Reproductive",
        label="",
    )

    # ── Step 4: Symptoms ──────────────────────────────────
    gr.HTML("<h3 style='color:#dda0dd; text-align:center;'>🔴 What are you feeling? / क्या महसूस हो रहा है?</h3>")

    symptoms = gr.CheckboxGroup(
        choices=[
            "Unusual bleeding / असामान्य रक्तस्राव",
            "Severe pelvic pain / तेज़ पेट दर्द",
            "Irregular periods / अनियमित माहवारी",
            "Unusual discharge / असामान्य स्राव",
            "Missed period / माहवारी न आना",
            "Fatigue / थकान",
            "Nausea / जी मिचलाना",
            "Severe headache / तेज़ सिरदर्द",
            "Swollen legs / पैर सूजना",
            "High fever / तेज़ बुखार",
        ],
        label="",
    )

    # ── Step 5: Speak or Write ────────────────────────────
    gr.HTML("<h3 style='color:#dda0dd; text-align:center;'>🎤 Or Speak / Write — बोलें या लिखें</h3>")

    with gr.Row():
        voice = gr.Audio(
            sources=["microphone"],
            type="filepath",
            label="🎤 Record / रिकॉर्ड करें",
            scale=1,
        )
        text = gr.Textbox(
            placeholder="पेट में दर्द है, माहवारी नहीं आई...",
            label="✍️ Write / लिखें",
            lines=3,
            scale=2,
        )

    # ── Analyze button ────────────────────────────────────
    btn = gr.Button(
        "🔍 Sakhi से पूछें / Ask Sakhi",
        variant="primary",
        size="lg",
    )

    # ── Output ────────────────────────────────────────────
    out = gr.HTML(
        value="""
        <div style='background:#1a0033; border-radius:16px; padding:30px;
                    text-align:center; font-family:Arial;'>
            <p style='color:#9370db; font-size:1.1em;'>
                🌸 Sakhi is waiting...<br>
                <span style='font-size:0.9em; color:#6a0dad;'>
                    Select your symptoms and click Ask Sakhi
                </span>
            </p>
        </div>
        """
    )

    # ── Wire button ───────────────────────────────────────
    btn.click(
        fn=analyze,
        inputs=[lang, pregnant, area, symptoms, voice, text],
        outputs=out,
    )

# ── Launch ────────────────────────────────────────────────
print("🚀 Launching SakhiAI...")
demo.launch(share=True, debug=False)